"""
Generator for Clinical Fracture Classifications (Campbell's Operative Orthopaedics 13th Edition).
Grounded in Campbell's 13th Ed trauma chapters, verified technique catalogs, and clinical principles.
"""

import json
import os

FRACTURE_CLASSIFICATIONS = [
  {
    "id": "schatzker",
    "name": "Phân loại Schatzker",
    "en_name": "Schatzker Tibial Plateau Fracture Classification",
    "bone": "Tibia (Plateau)",
    "bone_vi": "Mâm chày",
    "svg_ids": ["TibiaLeft", "TibiaRight", "l_Tibia", "PatellaLeft", "PatellaRight", "l_Patella"],
    "category": "Knee & Lower Leg",
    "chapter": 54,
    "chapter_title": "Fractures of the Lower Extremity",
    "pdf_page": 3078,
    "book_page": "2766",
    "description": "Phân loại kinh điển nhất cho gãy mâm chày dựa trên cơ chế chấn thương và tổn thương giải phẫu, chia làm 6 type từ năng lượng thấp đến năng lượng cao.",
    "types": [
      {
        "type": "Type I",
        "code": "Type I",
        "name": "Gãy tách rời mâm chày ngoài thuần túy (Split Fracture)",
        "description": "Gãy tách rời mâm chày ngoài thuần túy không có lún diện khớp. Thường gặp ở người trẻ tuổi với chất lượng xương xốp còn đặc chắc sau lực vẹo ngoài kèm dồn ép.",
        "desc": "Gãy tách rời mâm chày ngoài thuần túy không có lún diện khớp. Thường gặp ở người trẻ tuổi với chất lượng xương xốp còn đặc chắc sau lực vẹo ngoài kèm dồn ép.",
        "principles": "Nắn chỉnh giải phẫu diện khớp tuyệt đối (<2mm bậc thang). Cố định bằng 2-3 vít xốp rỗng nén ép có đệm (cannulated cancellous screws with washers) hoặc nẹp nâng đỡ (buttress plate) lối trước ngoài.",
        "management": "Nắn chỉnh giải phẫu diện khớp tuyệt đối (<2mm bậc thang). Cố định bằng 2-3 vít xốp rỗng nén ép có đệm (cannulated cancellous screws with washers) hoặc nẹp nâng đỡ (buttress plate) lối trước ngoài.",
        "technique_id": "54-14",
        "technique_title": "Open Reduction and Fixation of a Lateral Tibial Plateau Fracture",
        "button_label": "Xem Kỹ thuật 54-14 (ORIF Mâm chày ngoài)"
      },
      {
        "type": "Type II",
        "code": "Type II",
        "name": "Gãy tách rời KÈM lún mâm chày ngoài (Split-Depression)",
        "description": "Gãy tách rời kèm lún diện khớp mâm chày ngoài. Thể lâm sàng thường gặp nhất ở người trưởng thành và cao tuổi. Mặt khớp bị lún sâu vào vùng xương hành chày xốp.",
        "desc": "Gãy tách rời kèm lún diện khớp mâm chày ngoài. Thể lâm sàng thường gặp nhất ở người trưởng thành và cao tuổi. Mặt khớp bị lún sâu vào vùng xương hành chày xốp.",
        "principles": "Mở cửa sổ xương dưới diện lún, dùng cây đẩy nâng sụn (bone tamp) nâng mảng sụn khớp phẳng trở lại, ghép xương tự thân/đồng loại lấp đầy hốc rỗng, đặt nẹp nâng đỡ khóa ngoài bè xương nâng đỡ (rafting construct).",
        "management": "Mở cửa sổ xương dưới diện lún, dùng cây đẩy nâng sụn (bone tamp) nâng mảng sụn khớp phẳng trở lại, ghép xương tự thân/đồng loại lấp đầy hốc rỗng, đặt nẹp nâng đỡ khóa ngoài bè xương nâng đỡ (rafting construct).",
        "technique_id": "54-14",
        "technique_title": "Open Reduction and Fixation of a Lateral Tibial Plateau Fracture",
        "button_label": "Xem Kỹ thuật 54-14 (Nâng lún ghép xương & Nẹp khóa)"
      },
      {
        "type": "Type III",
        "code": "Type III",
        "name": "Gãy lún trung tâm mâm chày ngoài thuần túy (Depression)",
        "description": "Gãy lún sụn khớp mâm chày ngoài trung tâm mà vỏ xương mâm chày ngoài vẫn còn nguyên vẹn. Thường gặp ở bệnh nhân loãng xương sau chấn thương năng lượng thấp.",
        "desc": "Gãy lún sụn khớp mâm chày ngoài trung tâm mà vỏ xương mâm chày ngoài vẫn còn nguyên vẹn. Thường gặp ở bệnh nhân loãng xương sau chấn thương năng lượng thấp.",
        "principles": "Nâng diện khớp lún qua cửa sổ vỏ xương hành chày dưới hướng dẫn nội soi khớp (ARIF) hoặc C-arm, bơm xi măng sinh học hoặc nhồi xương xốp ghép, cố định hàng vít bè (rafting screws) hoặc nẹp bảo vệ.",
        "management": "Nâng diện khớp lún qua cửa sổ vỏ xương hành chày dưới hướng dẫn nội soi khớp (ARIF) hoặc C-arm, bơm xi măng sinh học hoặc nhồi xương xốp ghép, cố định hàng vít bè (rafting screws) hoặc nẹp bảo vệ.",
        "technique_id": "54-14",
        "technique_title": "Open Reduction and Fixation of a Lateral Tibial Plateau Fracture",
        "button_label": "Xem Kỹ thuật 54-14 (Nội soi nâng lún & Bắt vít bè)"
      },
      {
        "type": "Type IV",
        "code": "Type IV",
        "name": "Gãy mâm chày trong (Medial Tibial Plateau)",
        "description": "Gãy mâm chày trong do lực vẹo trong kèm dồn nén. Chấn thương năng lượng cao, liên kết chặt chẽ với trật khớp gối, đứt dây chằng chéo trước/sau và đe dọa tổn thương động tĩnh mạch khoeo.",
        "desc": "Gãy mâm chày trong do lực vẹo trong kèm dồn nén. Chấn thương năng lượng cao, liên kết chặt chẽ với trật khớp gối, đứt dây chằng chéo trước/sau và đe dọa tổn thương động tĩnh mạch khoeo.",
        "principles": "Bắt buộc mổ mở nắn chỉnh giải phẫu qua đường mổ sau-trong (posteromedial approach), đặt nẹp nâng đỡ mặt sau trong chống di lệch trượt xuống dưới, kiểm tra bắt mạch và doppler mạch khoeo.",
        "management": "Bắt buộc mổ mở nắn chỉnh giải phẫu qua đường mổ sau-trong (posteromedial approach), đặt nẹp nâng đỡ mặt sau trong chống di lệch trượt xuống dưới, kiểm tra bắt mạch và doppler mạch khoeo.",
        "technique_id": "54-15",
        "technique_title": "Posteromedial Exposure",
        "button_label": "Xem Kỹ thuật 54-15 (Đường mổ sau-trong mâm chày)"
      },
      {
        "type": "Type V",
        "code": "Type V",
        "name": "Gãy hai mâm chày (Bicondylar Tibial Plateau)",
        "description": "Gãy tách rời cả mâm chày trong và mâm chày ngoài, nhưng phần hành chày vẫn còn liên tục với thân xương chày (không mất liên tục hành - thân).",
        "desc": "Gãy tách rời cả mâm chày trong và mâm chày ngoài, nhưng phần hành chày vẫn còn liên tục với thân xương chày (không mất liên tục hành - thân).",
        "principles": "Kết hợp xương bằng hai nẹp (Dual plating qua đường mổ trước ngoài và sau trong) hoặc nẹp khóa ngoài đơn độc góc cố định chịu lực nếu phần mềm tổn thương nặng.",
        "management": "Kết hợp xương bằng hai nẹp (Dual plating qua đường mổ trước ngoài và sau trong) hoặc nẹp khóa ngoài đơn độc góc cố định chịu lực nếu phần mềm tổn thương nặng.",
        "technique_id": "54-16",
        "technique_title": "Open Reduction and Internal Fixation of Bicondylar Injuries",
        "button_label": "Xem Kỹ thuật 54-16 (Kết hợp xương hai nẹp mâm chày)"
      },
      {
        "type": "Type VI",
        "code": "Type VI",
        "name": "Mất liên tục hành - thân xương chày (Metaphyseal-Diaphyseal Dissociation)",
        "description": "Gãy mâm chày phức tạp kèm đứt rời hoàn toàn khối mâm chày - hành chày khỏi thân xương chày. Chấn thương năng lượng cực cao, nguy cơ hội chứng chèn ép khoang và hoại tử phần mềm.",
        "desc": "Gãy mâm chày phức tạp kèm đứt rời hoàn toàn khối mâm chày - hành chày khỏi thân xương chày. Chấn thương năng lượng cực cao, nguy cơ hội chứng chèn ép khoang và hoại tử phần mềm.",
        "principles": "Chiến lược hai thì (Span-scan-plan): Thì 1 đặt khung cố định ngoài bắc cầu qua gối giải phóng khoang; Thì 2 kết hợp xương dứt điểm bằng nẹp khóa hai bên hoặc khung vòng Ilizarov/Hybrid khi phần mềm nhăn da.",
        "management": "Chiến lược hai thì (Span-scan-plan): Thì 1 đặt khung cố định ngoài bắc cầu qua gối giải phóng khoang; Thì 2 kết hợp xương dứt điểm bằng nẹp khóa hai bên hoặc khung vòng Ilizarov/Hybrid khi phần mềm nhăn da.",
        "technique_id": "54-17",
        "technique_title": "Circular External Fixation (Watson)",
        "button_label": "Xem Kỹ thuật 54-17 (Khung cố định ngoài vòng Ilizarov/Watson)"
      }
    ],
    "techniques": ["54-14", "54-24", "54-15", "54-16", "54-17", "1-30", "1-31"]
  },
  {
    "id": "garden",
    "name": "Phân loại Garden",
    "en_name": "Garden Classification of Femoral Neck Fractures",
    "bone": "Femur (Neck)",
    "bone_vi": "Cổ xương đùi",
    "svg_ids": ["FemurLeft", "FemurRight", "l_Femur", "PelvicGirdle", "l_Pelvic_Girdle"],
    "category": "Hip & Pelvis",
    "chapter": 55,
    "chapter_title": "Fractures and Dislocations of the Hip",
    "pdf_page": 3144,
    "book_page": "2818",
    "description": "Phân loại gãy cổ xương đùi dựa trên hướng và độ di lệch của các bè xương trên phim X-quang thẳng, tiên lượng trực tiếp nguy cơ tổn thương động mạch mũ và hoại tử vô mạch chỏm xương đùi (AVN).",
    "types": [
      {
        "type": "Garden I",
        "code": "Garden I",
        "name": "Gãy không hoàn toàn / Cắm gắn dạng (Incomplete / Impacted Valgus)",
        "description": "Gãy dạng cắm gắn gập góc mở ra ngoài. Bè xương cổ - chỏm bị bẻ cong nhẹ theo chiều valgus. Vỏ xương dưới cổ đùi vẫn còn liên tục.",
        "desc": "Gãy dạng cắm gắn gập góc mở ra ngoài. Bè xương cổ - chỏm bị bẻ cong nhẹ theo chiều valgus. Vỏ xương dưới cổ đùi vẫn còn liên tục.",
        "principles": "Bảo tồn hoặc cố định trong bằng 3 vít xốp rỗng song song hình tam giác ngược để ngăn ngừa di lệch thứ phát (Per-cutaneous cannulated screws).",
        "management": "Bảo tồn hoặc cố định trong bằng 3 vít xốp rỗng song song hình tam giác ngược để ngăn ngừa di lệch thứ phát (Per-cutaneous cannulated screws).",
        "technique_id": "54-20",
        "technique_title": "Tension Band Wiring Fixation / Percutaneous Fixation",
        "button_label": "Xem Kỹ thuật 54-20 (Bắt vít xốp rỗng qua da)"
      },
      {
        "type": "Garden II",
        "code": "Garden II",
        "name": "Gãy hoàn toàn KHÔNG di lệch (Complete Non-displaced)",
        "description": "Đường gãy đi hết toàn bộ bề ngang cổ xương đùi nhưng các bè xương chịu lực vẫn thẳng hàng, không gập góc hay di lệch xoay.",
        "desc": "Đường gãy đi hết toàn bộ bề ngang cổ xương đùi nhưng các bè xương chịu lực vẫn thẳng hàng, không gập góc hay di lệch xoay.",
        "principles": "Bắt 3 vít xốp rỗng song song (hình tam giác đáy dưới) nén ép ổ gãy, cho phép vận động sớm không tỳ đè.",
        "management": "Bắt 3 vít xốp rỗng song song (hình tam giác đáy dưới) nén ép ổ gãy, cho phép vận động sớm không tỳ đè.",
        "technique_id": "54-20",
        "technique_title": "Tension Band Wiring Fixation / Percutaneous Fixation",
        "button_label": "Xem Kỹ thuật 54-20 (Bắt 3 vít xốp song song)"
      },
      {
        "type": "Garden III",
        "code": "Garden III",
        "name": "Gãy hoàn toàn di lệch MỘT PHẦN (Partially Displaced)",
        "description": "Đường gãy hoàn toàn kèm xoay khép chỏm xương đùi. Các bè xương chỏm không còn thẳng hàng với bè xương ổ cối mà xoay lệch hướng.",
        "desc": "Đường gãy hoàn toàn kèm xoay khép chỏm xương đùi. Các bè xương chỏm không còn thẳng hàng với bè xương ổ cối mà xoay lệch hướng.",
        "principles": "Người trẻ (<65 tuổi): Nắn kín hoặc mổ mở nắn chỉnh giải phẫu tuyệt đối, cố định bằng vít xốp hoặc DHS nẹp trượt bảo tồn chỏm. Người cao tuổi (>65 tuổi): Thay khớp háng bán phần (Bipolar) hoặc toàn phần (THA).",
        "management": "Người trẻ (<65 tuổi): Nắn kín hoặc mổ mở nắn chỉnh giải phẫu tuyệt đối, cố định bằng vít xốp hoặc DHS nẹp trượt bảo tồn chỏm. Người cao tuổi (>65 tuổi): Thay khớp háng bán phần (Bipolar) hoặc toàn phần (THA).",
        "technique_id": "54-21",
        "technique_title": "Open Reduction and Internal Fixation",
        "button_label": "Xem Kỹ thuật 54-21 (Mổ mở nắn chỉnh & Cố định)"
      },
      {
        "type": "Garden IV",
        "code": "Garden IV",
        "name": "Gãy hoàn toàn di lệch HOÀN TOÀN (Fully Displaced)",
        "description": "Chỏm xương đùi tách rời hoàn toàn và tự do trong ổ cối. Các bè xương của chỏm nằm song song với bè xương ổ cối. Toàn bộ cuống mạch cấp máu chỏm bị đứt rách.",
        "desc": "Chỏm xương đùi tách rời hoàn toàn và tự do trong ổ cối. Các bè xương của chỏm nằm song song với bè xương ổ cối. Toàn bộ cuống mạch cấp máu chỏm bị đứt rách.",
        "principles": "Chỉ định thay khớp háng nhân tạo: Thay khớp háng bán phần (Hemiarthroplasty/Bipolar) ở bệnh nhân lớn tuổi ít vận động; Thay khớp háng toàn phần (THA) ở bệnh nhân còn minh mẫn, hoạt động nhiều.",
        "management": "Chỉ định thay khớp háng nhân tạo: Thay khớp háng bán phần (Hemiarthroplasty/Bipolar) ở bệnh nhân lớn tuổi ít vận động; Thay khớp háng toàn phần (THA) ở bệnh nhân còn minh mẫn, hoạt động nhiều.",
        "technique_id": "54-22",
        "technique_title": "Sliding Hip Screw / Arthroplasty Fixation",
        "button_label": "Xem Kỹ thuật 54-22 (Nẹp trượt DHS / Thay khớp háng)"
      }
    ],
    "techniques": ["55-1", "55-2", "55-4", "54-20", "54-21", "54-22", "3-1", "6-1"]
  },
  {
    "id": "pauwels",
    "name": "Phân loại Pauwels",
    "en_name": "Pauwels Classification of Femoral Neck Fractures",
    "bone": "Femur (Neck)",
    "bone_vi": "Cổ xương đùi",
    "svg_ids": ["FemurLeft", "FemurRight", "l_Femur"],
    "category": "Hip & Pelvis",
    "chapter": 55,
    "chapter_title": "Fractures and Dislocations of the Hip",
    "pdf_page": 3144,
    "book_page": "2818",
    "description": "Dựa trên góc tạo bởi đường gãy và mặt phẳng nằm ngang, đánh giá lực trượt cắt (shear stress) tác động lên ổ gãy, tiên lượng mất vững cơ học và thất bại liền xương.",
    "types": [
      {
        "type": "Pauwels Type I",
        "code": "Pauwels Type I",
        "name": "Góc gãy < 30° (Lực nén ép ưu thế)",
        "description": "Đường gãy nằm ngang với góc < 30° so với mặt phẳng ngang. Trọng lượng cơ thể tạo ra lực nén ép hỗ trợ liền xương tự nhiên.",
        "desc": "Đường gãy nằm ngang với góc < 30° so với mặt phẳng ngang. Trọng lượng cơ thể tạo ra lực nén ép hỗ trợ liền xương tự nhiên.",
        "principles": "Cố định bằng 3 vít xốp rỗng song song (Cannulated screws). Tiên lượng liền xương rất cao (>95%).",
        "management": "Cố định bằng 3 vít xốp rỗng song song (Cannulated screws). Tiên lượng liền xương rất cao (>95%).",
        "technique_id": "54-20",
        "technique_title": "Percutaneous Cannulated Screw Fixation (54-20 / 55-1)",
        "button_label": "Xem Kỹ thuật 54-20 (Bắt vít xốp nén ép)"
      },
      {
        "type": "Pauwels Type II",
        "code": "Pauwels Type II",
        "name": "Góc gãy 30° - 50° (Lực trượt cắt trung bình)",
        "description": "Đường gãy chéo với góc từ 30° đến 50°. Bắt đầu xuất hiện lực trượt cắt có nguy cơ làm trượt ổ gãy khi chịu tải.",
        "desc": "Đường gãy chéo với góc từ 30° đến 50°. Bắt đầu xuất hiện lực trượt cắt có nguy cơ làm trượt ổ gãy khi chịu tải.",
        "principles": "Cố định vững chắc bằng nẹp trượt cổ đùi DHS (Dynamic Hip Screw) có vít chống xoay hoặc chùm 3 vít xốp có ren bám chắc.",
        "management": "Cố định vững chắc bằng nẹp trượt cổ đùi DHS (Dynamic Hip Screw) có vít chống xoay hoặc chùm 3 vít xốp có ren bám chắc.",
        "technique_id": "54-21",
        "technique_title": "Open Reduction and Internal Fixation (54-21 / 55-2)",
        "button_label": "Xem Kỹ thuật 54-21 (Cố định nẹp nén ép DHS)"
      },
      {
        "type": "Pauwels Type III",
        "code": "Pauwels Type III",
        "name": "Góc gãy > 50° (Lực trượt cắt cực lớn - Mất vững cao)",
        "description": "Đường gãy gần như thẳng đứng với góc > 50°. Lực trượt cắt chi phối hoàn toàn làm ổ gãy di lệch dọc, tỷ lệ khớp giả và tiêu chỏm cực cao.",
        "desc": "Đường gãy gần như thẳng đứng với góc > 50°. Lực trượt cắt chi phối hoàn toàn làm ổ gãy di lệch dọc, tỷ lệ khớp giả và tiêu chỏm cực cao.",
        "principles": "Yêu cầu kết hợp xương nẹp trượt DHS có nẹp chống trượt (derotation / buttress) hoặc đục xương sửa trục chỉnh góc vẹo ngoài (Pauwels Valgus Intertrochanteric Osteotomy) để chuyển lực trượt thành lực nén.",
        "management": "Yêu cầu kết hợp xương nẹp trượt DHS có nẹp chống trượt (derotation / buttress) hoặc đục xương sửa trục chỉnh góc vẹo ngoài (Pauwels Valgus Intertrochanteric Osteotomy) để chuyển lực trượt thành lực nén.",
        "technique_id": "54-22",
        "technique_title": "Sliding Hip Screw / Blade Plate / Osteotomy (54-22 / 55-9)",
        "button_label": "Xem Kỹ thuật 54-22 (Nẹp góc / Đục xương sửa trục)"
      }
    ],
    "techniques": ["54-20", "54-21", "54-22", "55-1", "55-2", "55-4", "6-1"]
  },
  {
    "id": "neer",
    "name": "Phân loại Neer",
    "en_name": "Neer Classification of Proximal Humeral Fractures",
    "bone": "Humerus (Proximal)",
    "bone_vi": "Đầu trên xương cánh tay",
    "svg_ids": ["HumerusLeft", "HumerusRight", "l_Humerus", "Scapula", "l_Scapula"],
    "category": "Shoulder & Arm",
    "chapter": 57,
    "chapter_title": "Fractures of the Shoulder, Arm, and Forearm",
    "pdf_page": 3288,
    "book_page": "2928",
    "description": "Phân loại dựa trên 4 thành phần giải phẫu (Chỏm xương, Củ lớn, Củ nhỏ, Thân xương). Một thành phần được coi là 1 mảnh (part) khi di lệch > 1 cm hoặc gập góc > 45°.",
    "types": [
      {
        "type": "One-Part",
        "code": "One-Part",
        "name": "Gãy một mảnh (Không di lệch hoặc di lệch tối thiểu)",
        "description": "Bất kể có bao nhiêu đường gãy, không có mảnh nào di lệch quá 1 cm hoặc gập góc quá 45°.",
        "desc": "Bất kể có bao nhiêu đường gãy, không có mảnh nào di lệch quá 1 cm hoặc gập góc quá 45°.",
        "principles": "Điều trị bảo tồn bằng treo tay bất động ngắn ngày (7-10 ngày), sau đó tập phục hồi chức năng sớm kiểu con lắc (Codman exercises).",
        "management": "Điều trị bảo tồn bằng treo tay bất động ngắn ngày (7-10 ngày), sau đó tập phục hồi chức năng sớm kiểu con lắc (Codman exercises).",
        "technique_id": "57-4",
        "technique_title": "Open Reduction and Internal Fixation of Proximal Humeral Fractures",
        "button_label": "Xem Kỹ thuật 57-4 (Điều trị bảo tồn / Nẹp khóa)"
      },
      {
        "type": "Two-Part",
        "code": "Two-Part",
        "name": "Gãy hai mảnh (Di lệch 1 thành phần)",
        "description": "Một trong 4 thành phần bị di lệch so với 3 thành phần còn lại. Thường gặp nhất là gãy cổ phẫu thuật hoặc gãy củ lớn di lệch.",
        "desc": "Một trong 4 thành phần bị di lệch so với 3 thành phần còn lại. Thường gặp nhất là gãy cổ phẫu thuật hoặc gãy củ lớn di lệch.",
        "principles": "Mổ mở kết hợp xương nẹp khóa đầu trên xương cánh tay (PHILOS plate) hoặc đóng đinh nội tủy có chốt lối vào đầu gần.",
        "management": "Mổ mở kết hợp xương nẹp khóa đầu trên xương cánh tay (PHILOS plate) hoặc đóng đinh nội tủy có chốt lối vào đầu gần.",
        "technique_id": "57-4",
        "technique_title": "Open Reduction and Internal Fixation of Proximal Humeral Fractures",
        "button_label": "Xem Kỹ thuật 57-4 (Nẹp khóa PHILOS đầu trên cánh tay)"
      },
      {
        "type": "Three-Part",
        "code": "Three-Part",
        "name": "Gãy ba mảnh (Di lệch 2 thành phần)",
        "description": "Gãy cổ phẫu thuật kèm vỡ di lệch củ lớn hoặc củ nhỏ. Chỏm xương bị cơ đối kháng xoay lệch trục.",
        "desc": "Gãy cổ phẫu thuật kèm vỡ di lệch củ lớn hoặc củ nhỏ. Chỏm xương bị cơ đối kháng xoay lệch trục.",
        "principles": "Mổ mở kết hợp xương nẹp khóa PHILOS, khâu chỉ bền neo giữ các gân chóp xoay vào các lỗ mắt nẹp để tăng độ vững giằng néo.",
        "management": "Mổ mở kết hợp xương nẹp khóa PHILOS, khâu chỉ bền neo giữ các gân chóp xoay vào các lỗ mắt nẹp để tăng độ vững giằng néo.",
        "technique_id": "57-4",
        "technique_title": "Open Reduction and Internal Fixation of Proximal Humeral Fractures",
        "button_label": "Xem Kỹ thuật 57-4 (ORIF Nẹp PHILOS & Khâu chóp xoay)"
      },
      {
        "type": "Four-Part",
        "code": "Four-Part",
        "name": "Gãy bốn mảnh (Di lệch cả 4 thành phần)",
        "description": "Tất cả 4 thành phần đều gãy rời và di lệch. Toàn bộ cuống mạch cấp máu từ động mạch mũ cánh tay bị đứt, nguy cơ hoại tử vô mạch chỏm > 90%.",
        "desc": "Tất cả 4 thành phần đều gãy rời và di lệch. Toàn bộ cuống mạch cấp máu từ động mạch mũ cánh tay bị đứt, nguy cơ hoại tử vô mạch chỏm > 90%.",
        "principles": "Người trẻ: Cố gắng nắn chỉnh bảo tồn chỏm bằng nẹp khóa và ghép xương xốp; Người cao tuổi loãng xương: Thay khớp vai bán phần (Hemiarthroplasty) hoặc Thay khớp vai đảo ngược (Reverse Shoulder Arthroplasty).",
        "management": "Người trẻ: Cố gắng nắn chỉnh bảo tồn chỏm bằng nẹp khóa và ghép xương xốp; Người cao tuổi loãng xương: Thay khớp vai bán phần (Hemiarthroplasty) hoặc Thay khớp vai đảo ngược (Reverse Shoulder Arthroplasty).",
        "technique_id": "57-5",
        "technique_title": "Anterolateral Acromial Approach for Internal Fixation of Proximal Humeral Fracture",
        "button_label": "Xem Kỹ thuật 57-5 (Thay khớp vai / Nẹp khóa lối trước ngoài)"
      },
      {
        "type": "Tuberosity Part",
        "code": "Tuberosity Part",
        "name": "Gãy củ lớn hoặc củ nhỏ đơn độc di lệch",
        "description": "Mảnh củ lớn di lệch lên trên hoặc ra sau > 5mm (ở vận động viên > 3mm) gây cấn kẹt khoang dưới mỏm cùng vai.",
        "desc": "Mảnh củ lớn di lệch lên trên hoặc ra sau > 5mm (ở vận động viên > 3mm) gây cấn kẹt khoang dưới mỏm cùng vai.",
        "principles": "Bắt vít xốp nén ép hoặc khâu neo chỉ bền phục hồi điểm bám gân cơ trên gai.",
        "management": "Bắt vít xốp nén ép hoặc khâu neo chỉ bền phục hồi điểm bám gân cơ trên gai.",
        "technique_id": "57-3",
        "technique_title": "Intramedullary Nailing of a Proximal Humeral Fracture",
        "button_label": "Xem Kỹ thuật 57-3 (Đinh nội tủy / Cố định củ lớn)"
      }
    ],
    "techniques": ["57-4", "57-5", "57-3", "12-1", "12-3"]
  },
  {
    "id": "gustilo",
    "name": "Phân loại Gustilo-Anderson (Gãy hở)",
    "en_name": "Gustilo-Anderson Open Fracture Classification",
    "bone": "Tibia / General Skeleton",
    "bone_vi": "Xương cẳng chân & Toàn thân",
    "svg_ids": ["TibiaLeft", "TibiaRight", "l_Tibia", "FibulaLeft", "FibulaRight", "l_Fibula", "FemurLeft", "FemurRight", "l_Femur"],
    "category": "Trauma & Fracture Reconstruction",
    "chapter": 53,
    "chapter_title": "General Principles of Fracture Treatment",
    "pdf_page": 2974,
    "book_page": "2662",
    "description": "Tiêu chuẩn vàng toàn cầu đánh giá tổn thương phần mềm, mức độ nhiễm bẩn, nguy cơ nhiễm trùng và chỉ định kháng sinh, cắt lọc và kết hợp xương trong gãy hở.",
    "types": [
      {
        "type": "Type I",
        "code": "Type I",
        "name": "Vết thương sạch < 1 cm",
        "description": "Vết rách da sạch dài dưới 1 cm, thường do đầu xương chọc thủng từ trong ra ngoài. Tổn thương cơ và mô mềm tối thiểu.",
        "desc": "Vết rách da sạch dài dưới 1 cm, thường do đầu xương chọc thủng từ trong ra ngoài. Tổn thương cơ và mô mềm tối thiểu.",
        "principles": "Cắt lọc rửa sạch vết thương trong 6 giờ đầu, kháng sinh Cephalosporin thế hệ 1, kết hợp xương vững chắc bằng đinh nội tủy chốt.",
        "management": "Cắt lọc rửa sạch vết thương trong 6 giờ đầu, kháng sinh Cephalosporin thế hệ 1, kết hợp xương vững chắc bằng đinh nội tủy chốt.",
        "technique_id": "53-2",
        "technique_title": "Irrigation and Debridement of Open Wounds",
        "button_label": "Xem Kỹ thuật 53-2 (Cắt lọc tưới rửa vết thương hở)"
      },
      {
        "type": "Type II",
        "code": "Type II",
        "name": "Vết thương 1 - 10 cm, không dập nát rộng",
        "description": "Vết thương rách da từ 1 đến 10 cm, không có dập nát cơ diện rộng, không có vạt da bong tróc mất nuôi dưỡng.",
        "desc": "Vết thương rách da từ 1 đến 10 cm, không có dập nát cơ diện rộng, không có vạt da bong tróc mất nuôi dưỡng.",
        "principles": "Cắt lọc triệt để lấy bỏ mô hoại tử, kháng sinh Cefazolin phối hợp Aminoglycoside, đóng đinh nội tủy chốt hoặc nẹp khóa.",
        "management": "Cắt lọc triệt để lấy bỏ mô hoại tử, kháng sinh Cefazolin phối hợp Aminoglycoside, đóng đinh nội tủy chốt hoặc nẹp khóa.",
        "technique_id": "53-2",
        "technique_title": "Irrigation and Debridement of Open Wounds",
        "button_label": "Xem Kỹ thuật 53-2 (Cắt lọc triệt để & KHX)"
      },
      {
        "type": "Type IIIA",
        "code": "Type IIIA",
        "name": "Vết thương > 10 cm, mô mềm ĐỦ che phủ xương",
        "description": "Chấn thương năng lượng cao, vết thương rộng > 10 cm, dập nát mô mềm nặng nhưng phần mềm sau cắt lọc vẫn đủ khả năng che phủ xương.",
        "desc": "Chấn thương năng lượng cao, vết thương rộng > 10 cm, dập nát mô mềm nặng nhưng phần mềm sau cắt lọc vẫn đủ khả năng che phủ xương.",
        "principles": "Cắt lọc nhiều thì (serial debridement), kháng sinh phổ rộng (Cephalosporin + Gentamicin, thêm Penicillin nếu nghi ngờ kỵ khí), đóng đinh nội tủy có chốt.",
        "management": "Cắt lọc nhiều thì (serial debridement), kháng sinh phổ rộng (Cephalosporin + Gentamicin, thêm Penicillin nếu nghi ngờ kỵ khí), đóng đinh nội tủy có chốt.",
        "technique_id": "54-11",
        "technique_title": "Intramedullary Nailing of Tibial Shaft Fractures",
        "button_label": "Xem Kỹ thuật 54-11 (Đinh nội tủy chốt xương chày)"
      },
      {
        "type": "Type IIIB",
        "code": "Type IIIB",
        "name": "Bong tróc màng xương, THIẾU mô mềm che phủ",
        "description": "Tổn thương mất mô mềm rộng, bong tróc màng xương diện rộng, lộ xương gãy. Không đủ phần mềm tại chỗ để che phủ xương gãy.",
        "desc": "Tổn thương mất mô mềm rộng, bong tróc màng xương diện rộng, lộ xương gãy. Không đủ phần mềm tại chỗ để che phủ xương gãy.",
        "principles": "Bất động khung cố định ngoài tạm thời, hút áp lực âm VAC, chuyển vạt cơ tại chỗ (vạt bụng chân/vạt dép) hoặc vạt da-cơ tự do vi phẫu che phủ xương.",
        "management": "Bất động khung cố định ngoài tạm thời, hút áp lực âm VAC, chuyển vạt cơ tại chỗ (vạt bụng chân/vạt dép) hoặc vạt da-cơ tự do vi phẫu che phủ xương.",
        "technique_id": "54-12",
        "technique_title": "External Fixation for Tibial Shaft Fractures",
        "button_label": "Xem Kỹ thuật 54-12 (Khung cố định ngoài cẳng chân)"
      },
      {
        "type": "Type IIIC",
        "code": "Type IIIC",
        "name": "Gãy xương hở KÈM TỔN THƯƠNG MẠCH MÁU CHÍNH",
        "description": "Gãy xương hở kèm tổn thương động mạch chính của chi cần phải tái thông/khâu nối mạch máu để duy trì sự sống của chi.",
        "desc": "Gãy xương hở kèm tổn thương động mạch chính của chi cần phải tái thông/khâu nối mạch máu để duy trì sự sống của chi.",
        "principles": "Cấp cứu tối khẩn: Đặt ống Shunt tạm thời lưu thông máu, cố định ngoài khung cứng vững, sau đó khâu nối/ghép mạch máu vi phẫu và mở cân dự phòng chèn ép khoang.",
        "management": "Cấp cứu tối khẩn: Đặt ống Shunt tạm thời lưu thông máu, cố định ngoài khung cứng vững, sau đó khâu nối/ghép mạch máu vi phẫu và mở cân dự phòng chèn ép khoang.",
        "technique_id": "53-2",
        "technique_title": "Irrigation and Debridement of Open Wounds",
        "button_label": "Xem Kỹ thuật 53-2 (Cắt lọc khẩn cấp & Tái thông mạch)"
      }
    ],
    "techniques": ["53-1", "53-2", "54-11", "54-12", "63-1"]
  },
  {
    "id": "young_burgess",
    "name": "Phân loại Young-Burgess (Gãy khung chậu)",
    "en_name": "Young-Burgess Pelvic Ring Disruption Classification",
    "bone": "Pelvic Girdle",
    "bone_vi": "Khung chậu & Vòng chậu",
    "svg_ids": ["PelvicGirdle", "l_Pelvic_Girdle", "Sacrum", "l_Sacrum"],
    "category": "Hip & Pelvis",
    "chapter": 56,
    "chapter_title": "Fractures of Acetabulum and Pelvis",
    "pdf_page": 3245,
    "book_page": "2886",
    "description": "Phân loại dựa trên hướng của lực chấn thương (Ép trước sau APC, Ép bên LC, Xé dọc VS) để dự báo tình trạng mất vững cơ học, tổn thương mạch máu chậu và nhu cầu truyền máu cấp cứu.",
    "types": [
      {
        "type": "LC (Lateral Compression)",
        "code": "LC",
        "name": "Ép bên (Lateral Compression - LC-I / LC-II / LC-III)",
        "description": "Lực va đập từ bên hông làm xoay trong nửa khung chậu, gãy cành mu ngang kèm gãy lún xương cùng cùng bên hoặc gãy cánh chậu hình lưỡi liềm (Crescent fracture).",
        "desc": "Lực va đập từ bên hông làm xoay trong nửa khung chậu, gãy cành mu ngang kèm gãy lún xương cùng cùng bên hoặc gãy cánh chậu hình lưỡi liềm (Crescent fracture).",
        "principles": "LC-I thường vững cơ học, điều trị bảo tồn; LC-II/III mất vững xoay cần nẹp cố định cánh chậu hoặc bắt vít xương cùng (Cancellous screw technique).",
        "management": "LC-I thường vững cơ học, điều trị bảo tồn; LC-II/III mất vững xoay cần nẹp cố định cánh chậu hoặc bắt vít xương cùng (Cancellous screw technique).",
        "technique_id": "53-5",
        "technique_title": "ASIF Cancellous Screw Technique",
        "button_label": "Xem Kỹ thuật 53-5 (Vít xốp nén ép cánh chậu - cùng)"
      },
      {
        "type": "APC (Anterior-Posterior Compression)",
        "code": "APC",
        "name": "Ép trước - sau (APC-I / APC-II / APC-III Cuốn sách mở)",
        "description": "Lực đè nén từ trước ra sau làm toác khớp mu (>2.5cm) và xé rách hệ thống dây chằng cùng chậu trước (Open-book injury). Nguy cơ rách đám rối tĩnh mạch chậu gây sốc mất máu tử vong.",
        "desc": "Lực đè nén từ trước ra sau làm toác khớp mu (>2.5cm) và xé rách hệ thống dây chằng cùng chậu trước (Open-book injury). Nguy cơ rách đám rối tĩnh mạch chậu gây sốc mất máu tử vong.",
        "principles": "Cấp cứu: Quấn đai ép chậu (pelvic binder) hoặc cố định ngoài tạm thời. Mổ phiên: Nẹp nén ép khớp mu lối trước (Anterior symphysis plating) kết hợp vít chậu sau nếu APC-III.",
        "management": "Cấp cứu: Quấn đai ép chậu (pelvic binder) hoặc cố định ngoài tạm thời. Mổ phiên: Nẹp nén ép khớp mu lối trước (Anterior symphysis plating) kết hợp vít chậu sau nếu APC-III.",
        "technique_id": "53-6",
        "technique_title": "Pin Insertion / Anterior Symphysis Plating (53-6 / 56-8)",
        "button_label": "Xem Kỹ thuật 53-6 (Nẹp cố định khớp mu lối trước)"
      },
      {
        "type": "VS (Vertical Shear)",
        "code": "VS",
        "name": "Xé dọc (Vertical Shear - Rơi từ trên cao)",
        "description": "Lực trượt dọc cực lớn (rơi cao dồn chân) làm đứt toàn bộ phức hợp dây chằng cùng chậu trước và sau, nửa khung chậu trượt hoàn toàn lên trên. Mất vững cơ học và huyết động tuyệt đối.",
        "desc": "Lực trượt dọc cực lớn (rơi cao dồn chân) làm đứt toàn bộ phức hợp dây chằng cùng chậu trước và sau, nửa khung chậu trượt hoàn toàn lên trên. Mất vững cơ học và huyết động tuyệt đối.",
        "principles": "Hồi sức sốc tích cực, kéo liên tục qua lồi củ chày nắn trượt, phẫu thuật kết hợp xương vững chắc bằng vít xốp qua da khớp cùng chậu (Iliosacral screws) kết hợp nẹp khớp mu hoặc khung chậu lối trước.",
        "management": "Hồi sức sốc tích cực, kéo liên tục qua lồi củ chày nắn trượt, phẫu thuật kết hợp xương vững chắc bằng vít xốp qua da khớp cùng chậu (Iliosacral screws) kết hợp nẹp khớp mu hoặc khung chậu lối trước.",
        "technique_id": "56-10",
        "technique_title": "Percutaneous Iliosacral Screw Fixation of Sacroiliac Disruptions and Sacral Fractures",
        "button_label": "Xem Kỹ thuật 56-10 (Bắt vít cùng chậu qua da Iliosacral)"
      }
    ],
    "techniques": ["53-5", "53-6", "56-8", "56-9", "56-10", "56-4"]
  },
  {
    "id": "letournel_judet",
    "name": "Phân loại Judet-Letournel",
    "en_name": "Judet-Letournel Acetabular Fracture Classification",
    "bone": "Acetabulum",
    "bone_vi": "Ổ cối khớp háng",
    "svg_ids": ["PelvicGirdle", "l_Pelvic_Girdle", "FemurLeft", "FemurRight", "l_Femur"],
    "category": "Hip & Pelvis",
    "chapter": 56,
    "chapter_title": "Fractures of Acetabulum and Pelvis",
    "pdf_page": 3210,
    "book_page": "2868",
    "description": "Phân loại giải phẫu 2 cột trụ (Cột trước - Iliopectineal, Cột sau - Ilioischial) và 2 thành (Thành trước, Thành sau). Chia thành 5 thể gãy cơ bản và 5 thể gãy phối hợp phức tạp.",
    "types": [
      {
        "type": "Thành trước / Cột trước",
        "code": "Thành trước / Cột trước",
        "name": "Gãy thành trước hoặc cột trước (Anterior Column / Wall)",
        "description": "Đường gãy đi qua nửa trước ổ cối, từ mào chậu qua cành mu, làm mất độ vững phía trước của chỏm xương đùi.",
        "desc": "Đường gãy đi qua nửa trước ổ cối, từ mào chậu qua cành mu, làm mất độ vững phía trước của chỏm xương đùi.",
        "principles": "Mổ mở nắn chỉnh qua đường mổ Ilioinguinal hoặc Stoppa cải biên, đặt nẹp tái tạo uốn cong dài dọc bờ trong mào chậu và gờ lược xương mu.",
        "management": "Mổ mở nắn chỉnh qua đường mổ Ilioinguinal hoặc Stoppa cải biên, đặt nẹp tái tạo uốn cong dài dọc bờ trong mào chậu và gờ lược xương mu.",
        "technique_id": "53-1",
        "technique_title": "Percutaneous Drainage / Ilioinguinal Plating Approach (53-1 / 56-1)",
        "button_label": "Xem Kỹ thuật 53-1 (Đường mổ Ilioinguinal & Nẹp cột trước)"
      },
      {
        "type": "Thành sau / Cột sau",
        "code": "Thành sau / Cột sau",
        "name": "Gãy thành sau hoặc cột sau (Posterior Column / Wall)",
        "description": "Thể gãy ổ cối thường gặp nhất, xảy ra khi trật khớp háng ra sau. Mảnh vỡ thành sau làm mất điểm tựa giữ chỏm xương đùi.",
        "desc": "Thể gãy ổ cối thường gặp nhất, xảy ra khi trật khớp háng ra sau. Mảnh vỡ thành sau làm mất điểm tựa giữ chỏm xương đùi.",
        "principles": "Mổ mở qua đường mổ Kocher-Langenbeck lối sau, nắn giải phẫu mặt sụn khớp, đặt nẹp nâng đỡ (spring plate / reconstruction plate) ôm khít bờ sau ổ cối.",
        "management": "Mổ mở qua đường mổ Kocher-Langenbeck lối sau, nắn giải phẫu mặt sụn khớp, đặt nẹp nâng đỡ (spring plate / reconstruction plate) ôm khít bờ sau ổ cối.",
        "technique_id": "53-2",
        "technique_title": "Kocher-Langenbeck Approach and Posterior Wall Plating (53-2 / 56-2)",
        "button_label": "Xem Kỹ thuật 53-2 (Đường mổ Kocher-Langenbeck & Nẹp thành sau)"
      },
      {
        "type": "Hai cột / Chữ T",
        "code": "Hai cột / Chữ T",
        "name": "Gãy hai cột hoặc gãy chữ T (Both-Column / T-Shaped)",
        "description": "Toàn bộ diện khớp ổ cối bị tách rời khỏi trục khung chậu (Floating acetabulum). Tổn thương nội khớp cực kỳ phức tạp.",
        "desc": "Toàn bộ diện khớp ổ cối bị tách rời khỏi trục khung chậu (Floating acetabulum). Tổn thương nội khớp cực kỳ phức tạp.",
        "principles": "Phẫu thuật đường mổ rộng kết hợp (Ilioinguinal + Kocher-Langenbeck hoặc Extended Iliofemoral) hoặc Stoppa cải biên để tái tạo và nẹp cố định cả hai cột.",
        "management": "Phẫu thuật đường mổ rộng kết hợp (Ilioinguinal + Kocher-Langenbeck hoặc Extended Iliofemoral) hoặc Stoppa cải biên để tái tạo và nẹp cố định cả hai cột.",
        "technique_id": "53-3",
        "technique_title": "Extensile Combined Approaches for Both-Column Plating (53-3 / 56-3)",
        "button_label": "Xem Kỹ thuật 53-3 (Đường mổ kết hợp & Nẹp hai cột)"
      }
    ],
    "techniques": ["53-1", "53-2", "53-3", "56-1", "56-2", "56-3"]
  },
  {
    "id": "denis_spine",
    "name": "Phân loại Denis (3 cột trụ cột sống)",
    "en_name": "Denis Three-Column Spine Classification",
    "bone": "Thoracic & Lumbar Spine",
    "bone_vi": "Cột sống ngực & thắt lưng",
    "svg_ids": ["ThoracicVertebrae", "LumbarVertebrae", "l_Thoracic_Vertebrae", "l_Lumbar_Vertebrae"],
    "category": "Spine",
    "chapter": 41,
    "chapter_title": "Fractures, Dislocations, and Fracture-Dislocations of the Spine",
    "pdf_page": 1952,
    "book_page": "1757",
    "description": "Mô hình 3 cột trụ kinh điển: Cột trước (Dây chằng dọc trước + 2/3 trước thân đốt), Cột giữa (1/3 sau thân đốt + Dây chằng dọc sau), Cột sau (Cung cuống sống, bản sống, gai sau). Tổn thương cột giữa quyết định tính mất vững thần kinh và cơ học.",
    "types": [
      {
        "type": "Gãy nén (Compression)",
        "code": "Gãy nén",
        "name": "Gãy lún nén đơn thuần cột trước (Compression Fracture)",
        "description": "Chỉ tổn thương cột trước do lực uốn gập. Cột giữa và cột sau hoàn toàn nguyên vẹn. Cơ học vững, không chèn ép tủy sống.",
        "desc": "Chỉ tổn thương cột trước do lực uốn gập. Cột giữa và cột sau hoàn toàn nguyên vẹn. Cơ học vững, không chèn ép tủy sống.",
        "principles": "Điều trị bảo tồn bằng nẹp lưng áo TLSO hoặc bơm xi măng sinh học tạo hình thân đốt sống (Vertebroplasty/Kyphoplasty) nếu đau nhiều do loãng xương.",
        "management": "Điều trị bảo tồn bằng nẹp lưng áo TLSO hoặc bơm xi măng sinh học tạo hình thân đốt sống (Vertebroplasty/Kyphoplasty) nếu đau nhiều do loãng xương.",
        "technique_id": "38-1",
        "technique_title": "Interlaminar Epidural / Vertebral Body Procedures (38-1 / 37-1)",
        "button_label": "Xem Kỹ thuật 38-1 (Điều trị bảo tồn / Bơm xi măng)"
      },
      {
        "type": "Gãy nổ (Burst Fracture)",
        "code": "Gãy nổ",
        "name": "Gãy nhiều mảnh vỡ cột trước và cột giữa (Burst Fracture)",
        "description": "Tổn thương dập vỡ cả cột trước và cột giữa do lực dồn ép dọc trục. Mảnh xương vỡ của cột giữa lồi bắn vào ống sống gây chèn ép tủy hoặc đuôi ngựa.",
        "desc": "Tổn thương dập vỡ cả cột trước và cột giữa do lực dồn ép dọc trục. Mảnh xương vỡ của cột giữa lồi bắn vào ống sống gây chèn ép tủy hoặc đuôi ngựa.",
        "principles": "Mất vững cơ học hoặc có khiếm khuyết thần kinh: Phẫu thuật giải ép ống sống, nắn chỉnh gù vẹo và cố định cột sống bằng nẹp vít cuống sống (Pedicle screw fixation) có thể kèm cắt thân đốt lối trước.",
        "management": "Mất vững cơ học hoặc có khiếm khuyết thần kinh: Phẫu thuật giải ép ống sống, nắn chỉnh gù vẹo và cố định cột sống bằng nẹp vít cuống sống (Pedicle screw fixation) có thể kèm cắt thân đốt lối trước.",
        "technique_id": "38-2",
        "technique_title": "Pedicle Screw Fixation & Decompression (38-2 / 41-15)",
        "button_label": "Xem Kỹ thuật 38-2 (Nẹp vít cuống sống & Giải ép ống sống)"
      },
      {
        "type": "Gãy uốn căng (Seat-belt / Chance)",
        "code": "Gãy uốn căng",
        "name": "Tổn thương uốn căng xé rách cột giữa và sau (Chance Fracture)",
        "description": "Tổn thương đứt rách cột sau và cột giữa do lực uốn gập quá mức quanh trục xoay phía trước (tai nạn thắt dây an toàn xe hơi).",
        "desc": "Tổn thương đứt rách cột sau và cột giữa do lực uốn gập quá mức quanh trục xoay phía trước (tai nạn thắt dây an toàn xe hơi).",
        "principles": "Phẫu thuật nắn ép cột sau, hàn xương lối sau và cố định bằng nẹp vít cuống sống nén ép để phục hồi sức căng dây chằng sau.",
        "management": "Phẫu thuật nắn ép cột sau, hàn xương lối sau và cố định bằng nẹp vít cuống sống nén ép để phục hồi sức căng dây chằng sau.",
        "technique_id": "38-3",
        "technique_title": "Posterior Spinal Stabilization for Chance Fracture (38-3 / 41-15)",
        "button_label": "Xem Kỹ thuật 38-3 (Nẹp vít cuống sống nén ép cột sau)"
      },
      {
        "type": "Gãy trật (Fracture-Dislocation)",
        "code": "Gãy trật",
        "name": "Gãy trật đứt rách cả 3 cột trụ (Fracture-Dislocation)",
        "description": "Đứt gãy hoàn toàn cả 3 cột trụ do lực xoay vặn, xé trượt hoặc cắt ngang. Cực kỳ mất vững, tỷ lệ tổn thương tủy sống hoàn toàn rất cao.",
        "desc": "Đứt gãy hoàn toàn cả 3 cột trụ do lực xoay vặn, xé trượt hoặc cắt ngang. Cực kỳ mất vững, tỷ lệ tổn thương tủy sống hoàn toàn rất cao.",
        "principles": "Mổ cấp cứu nắn trật, giải phóng chèn ép tủy và cố định vững chắc đa tầng bằng nẹp vít cuống sống lối sau kết hợp hàn xương.",
        "management": "Mổ cấp cứu nắn trật, giải phóng chèn ép tủy và cố định vững chắc đa tầng bằng nẹp vít cuống sống lối sau kết hợp hàn xương.",
        "technique_id": "38-5",
        "technique_title": "Multi-Level Reduction and Instrumentation (38-5 / 41-15)",
        "button_label": "Xem Kỹ thuật 38-5 (Nắn trật & Cố định đa tầng)"
      }
    ],
    "techniques": ["38-1", "38-2", "38-3", "38-4", "38-5", "37-1", "41-15", "41-16"]
  },
  {
    "id": "danis_weber",
    "name": "Phân loại Danis-Weber & Lauge-Hansen",
    "en_name": "Danis-Weber & Lauge-Hansen Ankle Fracture Classification",
    "bone": "Fibula & Ankle (Malleoli)",
    "bone_vi": "Cổ chân & Mắt cá ngoài",
    "svg_ids": ["FibulaLeft", "FibulaRight", "l_Fibula", "TarsalsLeft", "TarsalsRight", "l_Tarsals"],
    "category": "Foot & Ankle",
    "chapter": 54,
    "chapter_title": "Fractures of the Lower Extremity",
    "pdf_page": 3026,
    "book_page": "2720",
    "description": "Phân loại gãy mắt cá ngoài xương mác dựa trên vị trí đường gãy so với khớp chày-mác dưới (Syndesmosis) để tiên lượng độ vững của mộng chày-sên.",
    "types": [
      {
        "type": "Weber A",
        "code": "Weber A",
        "name": "Gãy dưới mức khớp chày mác dưới (Infrasyndesmotic)",
        "description": "Đường gãy ngang mắt cá ngoài nằm DƯỚI mức khe khớp chày sên. Khớp chày mác dưới và màng gian cốt hoàn toàn nguyên vẹn.",
        "desc": "Đường gãy ngang mắt cá ngoài nằm DƯỚI mức khe khớp chày sên. Khớp chày mác dưới và màng gian cốt hoàn toàn nguyên vẹn.",
        "principles": "Gãy vững: Bó bột hoặc nẹp cổ chân đi bộ 4-6 tuần. Gãy di lệch hoặc kèm gãy mắt cá trong: Mổ mở kết hợp xương nẹp 1/3 ống hoặc néo ép số 8.",
        "management": "Gãy vững: Bó bột hoặc nẹp cổ chân đi bộ 4-6 tuần. Gãy di lệch hoặc kèm gãy mắt cá trong: Mổ mở kết hợp xương nẹp 1/3 ống hoặc néo ép số 8.",
        "technique_id": "54-1",
        "technique_title": "Fixation of the Lateral Malleolus",
        "button_label": "Xem Kỹ thuật 54-1 (Kết hợp xương mắt cá ngoài nẹp 1/3)"
      },
      {
        "type": "Weber B",
        "code": "Weber B",
        "name": "Gãy ngang mức khớp chày mác dưới (Transsyndesmotic)",
        "description": "Đường gãy chéo xoắn xương mác chạy ngang qua khe khớp chày mác dưới. Khớp chày mác dưới có thể bị rách một phần (thường do cơ chế xoay ngoài).",
        "desc": "Đường gãy chéo xoắn xương mác chạy ngang qua khe khớp chày mác dưới. Khớp chày mác dưới có thể bị rách một phần (thường do cơ chế xoay ngoài).",
        "principles": "Nếu di lệch > 2mm hoặc mất vững khớp chày sên: Mổ mở kết hợp xương nẹp 1/3 ống và ốc ép gian mảnh. Kiểm tra thử nghiệm Hook test; nếu lỏng khớp chày mác thì bắt thêm vít cố định khớp chày mác dưới (Syndesmotic screw).",
        "management": "Nếu di lệch > 2mm hoặc mất vững khớp chày sên: Mổ mở kết hợp xương nẹp 1/3 ống và ốc ép gian mảnh. Kiểm tra thử nghiệm Hook test; nếu lỏng khớp chày mác thì bắt thêm vít cố định khớp chày mác dưới (Syndesmotic screw).",
        "technique_id": "54-2",
        "technique_title": "Fixation of the Medial Malleolus",
        "button_label": "Xem Kỹ thuật 54-2 (ORIF Mắt cá trong & ngoài)"
      },
      {
        "type": "Weber C",
        "code": "Weber C",
        "name": "Gãy trên mức khớp chày mác dưới (Suprasyndesmotic)",
        "description": "Đường gãy xương mác nằm TRÊN khớp chày mác dưới (có thể gãy cao tới cổ xương mác - tổn thương Maisonneuve). Toàn bộ khớp chày mác dưới và màng gian cốt bị rách toác. Mộng chày sên mất vững hoàn toàn.",
        "desc": "Đường gãy xương mác nằm TRÊN khớp chày mác dưới (có thể gãy cao tới cổ xương mác - tổn thương Maisonneuve). Toàn bộ khớp chày mác dưới và màng gian cốt bị rách toác. Mộng chày sên mất vững hoàn toàn.",
        "principles": "Bắt buộc mổ kết hợp xương nẹp nén ép xương mác KÈM bắt vít cố định khớp chày mác dưới (Syndesmotic screws) hoặc dây néo nén ép đàn hồi (TightRope) để khóa mộng chày mác.",
        "management": "Bắt buộc mổ kết hợp xương nẹp nén ép xương mác KÈM bắt vít cố định khớp chày mác dưới (Syndesmotic screws) hoặc dây néo nén ép đàn hồi (TightRope) để khóa mộng chày mác.",
        "technique_id": "54-3",
        "technique_title": "Repair of the Deltoid Ligament and Internal Fixation of the Lateral Malleolus",
        "button_label": "Xem Kỹ thuật 54-3 (ORIF Xương mác cao & Khâu dây chằng)"
      }
    ],
    "techniques": ["54-1", "54-2", "54-3", "54-4", "54-6"]
  },
  {
    "id": "hawkins",
    "name": "Phân loại Hawkins (Gãy cổ xương sên)",
    "en_name": "Hawkins Talar Neck Fracture Classification",
    "bone": "Talus",
    "bone_vi": "Xương sên",
    "svg_ids": ["TarsalsLeft", "TarsalsRight", "l_Tarsals"],
    "category": "Foot & Ankle",
    "chapter": 88,
    "chapter_title": "Fractures and Dislocations of the Foot",
    "pdf_page": 4767,
    "book_page": "4306",
    "description": "Phân loại gãy cổ xương sên dự báo tỷ lệ hoại tử vô mạch chỏm sên (Avascular Necrosis - AVN) dựa trên phạm vi trật khớp dưới sên và khớp chày sên.",
    "types": [
      {
        "type": "Type I",
        "code": "Type I",
        "name": "Gãy cổ sên dọc không di lệch (Non-displaced)",
        "description": "Đường gãy dọc qua cổ xương sên nhưng không di lệch. Cả khớp chày sên và khớp sên gót đều giữ nguyên quan hệ giải phẫu. Nguy cơ AVN < 10%.",
        "desc": "Đường gãy dọc qua cổ xương sên nhưng không di lệch. Cả khớp chày sên và khớp sên gót đều giữ nguyên quan hệ giải phẫu. Nguy cơ AVN < 10%.",
        "principles": "Bó bột cẳng bàn chân không tỳ đè 8-12 tuần hoặc bắt vít xốp qua da để chống di lệch thứ phát.",
        "management": "Bó bột cẳng bàn chân không tỳ đè 8-12 tuần hoặc bắt vít xốp qua da để chống di lệch thứ phát.",
        "technique_id": "88-8",
        "technique_title": "Open Reduction of the Talar Neck",
        "button_label": "Xem Kỹ thuật 88-8 (Bó bột / Bắt vít xốp qua da)"
      },
      {
        "type": "Type II",
        "code": "Type II",
        "name": "Gãy có di lệch KÈM trật khớp sên - gót",
        "description": "Gãy cổ sên di lệch kèm bán trật hoặc trật khớp sên gót (khớp chày sên còn nguyên vẹn). Nguy cơ hoại tử vô mạch AVN từ 40% đến 50%.",
        "desc": "Gãy cổ sên di lệch kèm bán trật hoặc trật khớp sên gót (khớp chày sên còn nguyên vẹn). Nguy cơ hoại tử vô mạch AVN từ 40% đến 50%.",
        "principles": "Phẫu thuật nắn mở cấp cứu nắn trật khớp sên gót, cố định bằng 2 vít xốp rỗng bắt từ sau ra trước hoặc từ trước ra sau.",
        "management": "Phẫu thuật nắn mở cấp cứu nắn trật khớp sên gót, cố định bằng 2 vít xốp rỗng bắt từ sau ra trước hoặc từ trước ra sau.",
        "technique_id": "88-8",
        "technique_title": "Open Reduction of the Talar Neck",
        "button_label": "Xem Kỹ thuật 88-8 (Mổ mở nắn trật & Bắt ốc cổ sên)"
      },
      {
        "type": "Type III",
        "code": "Type III",
        "name": "Gãy di lệch KÈM trật CẢ KHỚP SÊN - GÓT VÀ CHÀY - SÊN",
        "description": "Thân xương sên bị trật bật ra khỏi gọng chày mác và khớp sên gót, xoay lật ra phía sau trong. Nguy cơ hoại tử vô mạch AVN lên tới 85% - 90%.",
        "desc": "Gãy di lệch KÈM trật CẢ KHỚP SÊN - GÓT VÀ CHÀY - SÊN",
        "principles": "Mổ cấp cứu tuyệt đối: Đường mổ kép (trước trong và trước ngoài), nắn chỉnh thân sên vào lại gọng chày sên, bảo tồn tối đa dây chằng và cuống mạch còn lại.",
        "management": "Mổ cấp cứu tuyệt đối: Đường mổ kép (trước trong và trước ngoài), nắn chỉnh thân sên vào lại gọng chày sên, bảo tồn tối đa dây chằng và cuống mạch còn lại.",
        "technique_id": "88-8",
        "technique_title": "Open Reduction of the Talar Neck",
        "button_label": "Xem Kỹ thuật 88-8 (Đường mổ đôi cấp cứu nắn trật thân sên)"
      },
      {
        "type": "Type IV",
        "code": "Type IV",
        "name": "Gãy Type III KÈM trật khớp sên - thuyền",
        "description": "Bao gồm toàn bộ thương tổn của Type III kèm theo trật khớp sên thuyền. Chỏm sên mất liên kết hoàn toàn, nguy cơ hoại tử vô mạch gần như 100%.",
        "desc": "Bao gồm toàn bộ thương tổn của Type III kèm theo trật khớp sên thuyền. Chỏm sên mất liên kết hoàn toàn, nguy cơ hoại tử vô mạch gần như 100%.",
        "principles": "Mổ mở nắn trật đa khớp, cố định vững chắc, theo dõi dấu hiệu Hawkins sign (vệt tiêu xương dưới sụn) ở tuần 6-8 để tiên lượng mạch máu sống sót.",
        "management": "Mổ mở nắn trật đa khớp, cố định vững chắc, theo dõi dấu hiệu Hawkins sign (vệt tiêu xương dưới sụn) ở tuần 6-8 để tiên lượng mạch máu sống sót.",
        "technique_id": "88-9",
        "technique_title": "Onlay Graft Technique Through a Posterior Approach (Johnson)",
        "button_label": "Xem Kỹ thuật 88-9 (Nắn trật đa khớp & Ghép xương sên)"
      }
    ],
    "techniques": ["88-8", "88-9", "88-11", "88-12", "88-13"]
  },
  {
    "id": "frykman",
    "name": "Phân loại Frykman",
    "en_name": "Frykman Distal Radius Fracture Classification",
    "bone": "Radius (Distal)",
    "bone_vi": "Đầu dưới xương quay",
    "svg_ids": ["RadiusLeft", "RadiusRight", "l_Radius", "CarpalsLeft", "CarpalsRight", "l_Carpals"],
    "category": "Hand & Wrist",
    "chapter": 57,
    "chapter_title": "Fractures of the Shoulder, Arm, and Forearm",
    "pdf_page": 3333,
    "book_page": "2990",
    "description": "Phân loại dựa trên sự thương tổn của khớp quay - cổ tay (Radiocarpal), khớp quay - trụ dưới (DRUJ) và gãy kèm mỏm trâm trụ (Ulnar styloid fracture).",
    "types": [
      {
        "type": "Type I & II",
        "code": "Type I & II",
        "name": "Gãy ngoài khớp (Type I: Không gãy trâm trụ; Type II: Kèm gãy trâm trụ)",
        "description": "Gãy đầu dưới xương quay ngoài khớp hoàn toàn không phạm diện sụn (Gãy Colles hoặc Smith).",
        "desc": "Gãy đầu dưới xương quay ngoài khớp hoàn toàn không phạm diện sụn (Gãy Colles hoặc Smith).",
        "principles": "Nắn chỉnh kín bó bột cẳng bàn tay rạch dọc. Nếu di lệch thứ phát hoặc ngắn xương > 3mm: Mổ mở kết hợp xương nẹp khóa mặt lòng (Volar locking plate).",
        "management": "Nắn chỉnh kín bó bột cẳng bàn tay rạch dọc. Nếu di lệch thứ phát hoặc ngắn xương > 3mm: Mổ mở kết hợp xương nẹp khóa mặt lòng (Volar locking plate).",
        "technique_id": "57-13",
        "technique_title": "Closed Reduction and Percutaneous Pinning of Distal Radial Fracture (Glickel et al.)",
        "button_label": "Xem Kỹ thuật 57-13 (Nắn kín & Xuyên kim K-wire)"
      },
      {
        "type": "Type III & IV",
        "code": "Type III & IV",
        "name": "Gãy phạm khớp quay - cổ tay (Type III: Không trâm trụ; Type IV: Kèm trâm trụ)",
        "description": "Đường gãy lan vào diện sụn khớp quay cổ tay, làm mất độ nhẵn bóng của diện khớp chịu lực.",
        "desc": "Đường gãy lan vào diện sụn khớp quay cổ tay, làm mất độ nhẵn bóng của diện khớp chịu lực.",
        "principles": "Yêu cầu phục hồi phẳng diện khớp (<1-2mm bậc thang). Mổ mở kết hợp xương bằng nẹp khóa mặt lòng (Volar locking plate) nén ép diện khớp.",
        "management": "Yêu cầu phục hồi phẳng diện khớp (<1-2mm bậc thang). Mổ mở kết hợp xương bằng nẹp khóa mặt lòng (Volar locking plate) nén ép diện khớp.",
        "technique_id": "57-15",
        "technique_title": "Volar Plate Fixation of Fracture of the Distal Radius (Chung)",
        "button_label": "Xem Kỹ thuật 57-15 (Nẹp khóa mặt lòng Volar plate)"
      },
      {
        "type": "Type V & VI",
        "code": "Type V & VI",
        "name": "Gãy phạm khớp quay - trụ dưới DRUJ (Type V: Không trâm trụ; Type VI: Kèm trâm trụ)",
        "description": "Đường gãy liên quan tới khuyết trụ của xương quay, đe dọa mất vững khớp quay trụ dưới và hạn chế tầm vận động sấp ngửa cẳng tay.",
        "desc": "Đường gãy liên quan tới khuyết trụ của xương quay, đe dọa mất vững khớp quay trụ dưới và hạn chế tầm vận động sấp ngửa cẳng tay.",
        "principles": "Nẹp khóa mặt lòng kết hợp kiểm tra độ vững DRUJ; nếu lỏng khớp chày mác dưới cần xuyên kim K-wire cố định khớp quay trụ dưới tạm thời.",
        "management": "Nẹp khóa mặt lòng kết hợp kiểm tra độ vững DRUJ; nếu lỏng khớp chày mác dưới cần xuyên kim K-wire cố định khớp quay trụ dưới tạm thời.",
        "technique_id": "57-14",
        "technique_title": "External Fixation of Fracture of the Distal Radius",
        "button_label": "Xem Kỹ thuật 57-14 (Khung cố định ngoài bắc cầu)"
      },
      {
        "type": "Type VII & VIII",
        "code": "Type VII & VIII",
        "name": "Gãy nội khớp phức tạp phạm CẢ KHỚP QUAY CỔ TAY VÀ KHỚP QUAY TRỤ DƯỚI",
        "description": "Gãy vỡ vụn nội khớp 4 mảnh phức tạp liên quan cả hai khớp. Thể tổn thương nặng nhất trong phân loại Frykman.",
        "desc": "Gãy nội khớp phức tạp phạm CẢ KHỚP QUAY CỔ TAY VÀ KHỚP QUAY TRỤ DƯỚI",
        "principles": "Mổ mở kết hợp xương nẹp khóa mặt lòng đa trục kết hợp ghép xương xốp hoặc khung cố định ngoài bắc cầu qua cổ tay.",
        "management": "Mổ mở kết hợp xương nẹp khóa mặt lòng đa trục kết hợp ghép xương xốp hoặc khung cố định ngoài bắc cầu qua cổ tay.",
        "technique_id": "57-15",
        "technique_title": "Volar Plate Fixation of Fracture of the Distal Radius (Chung)",
        "button_label": "Xem Kỹ thuật 57-15 (Nẹp khóa Volar đa trục & Ghép xương)"
      }
    ],
    "techniques": ["57-13", "57-14", "57-15", "57-16"]
  },
  {
    "id": "mason",
    "name": "Phân loại Mason (Chỏm xương quay)",
    "en_name": "Mason Radial Head Fracture Classification",
    "bone": "Radius (Head) & Elbow",
    "bone_vi": "Chỏm xương quay & Khớp khuỷu",
    "svg_ids": ["RadiusLeft", "RadiusRight", "l_Radius", "UlnaLeft", "UlnaRight", "l_Ulna"],
    "category": "Elbow & Forearm",
    "chapter": 57,
    "chapter_title": "Fractures of the Shoulder, Arm, and Forearm",
    "pdf_page": 3309,
    "book_page": "2972",
    "description": "Phân loại gãy chỏm xương quay kinh điển chỉ định giữa điều trị bảo tồn, kết hợp xương nẹp vít vi phẫu hoặc phẫu thuật thay chỏm quay nhân tạo.",
    "types": [
      {
        "type": "Type I",
        "code": "Type I",
        "name": "Gãy mép không di lệch (Di lệch < 2mm)",
        "description": "Gãy bờ mép chỏm xương quay không di lệch hoặc di lệch < 2mm. Không có cản trở cơ học khi thực hiện vận động sấp ngửa cẳng tay.",
        "desc": "Gãy bờ mép chỏm xương quay không di lệch hoặc di lệch < 2mm. Không có cản trở cơ học khi thực hiện vận động sấp ngửa cẳng tay.",
        "principles": "Chọc hút giảm áp máu tụ trong bao khớp khuỷu, bất động treo tay trong vài ngày rồi tập vận động sớm để phòng tránh cứng khớp khuỷu.",
        "management": "Chọc hút giảm áp máu tụ trong bao khớp khuỷu, bất động treo tay trong vài ngày rồi tập vận động sớm để phòng tránh cứng khớp khuỷu.",
        "technique_id": "57-9",
        "technique_title": "Open Reduction and Internal Fixation of Radial Head Fracture",
        "button_label": "Xem Kỹ thuật 57-9 (Bảo tồn / Chọc hút dịch khớp)"
      },
      {
        "type": "Type II",
        "code": "Type II",
        "name": "Gãy tách rời có di lệch > 2mm hoặc gập góc",
        "description": "Gãy tách rời một phần chu vi chỏm quay có di lệch > 2mm, có mảnh xương kẹt gây hạn chế tầm vận động sấp ngửa.",
        "desc": "Gãy tách rời một phần chu vi chỏm quay có di lệch > 2mm, có mảnh xương kẹt gây hạn chế tầm vận động sấp ngửa.",
        "principles": "Mổ mở kết hợp xương nắn giải phẫu, bắt vít chìm không đầu (Herbert/headless screws) hoặc nẹp vi phẫu đặt tại vùng an toàn (Safe zone).",
        "management": "Mổ mở kết hợp xương nắn giải phẫu, bắt vít chìm không đầu (Herbert/headless screws) hoặc nẹp vi phẫu đặt tại vùng an toàn (Safe zone).",
        "technique_id": "57-9",
        "technique_title": "Open Reduction and Internal Fixation of Radial Head Fracture",
        "button_label": "Xem Kỹ thuật 57-9 (Bắt ốc chìm không đầu Herbert)"
      },
      {
        "type": "Type III",
        "code": "Type III",
        "name": "Gãy vỡ vụn toàn bộ chỏm xương quay",
        "description": "Chỏm xương quay vỡ nát thành nhiều mảnh rời không thể kết hợp xương nẹp vít phục hồi nguyên vẹn diện khớp.",
        "desc": "Chỏm xương quay vỡ nát thành nhiều mảnh rời không thể kết hợp xương nẹp vít phục hồi nguyên vẹn diện khớp.",
        "principles": "Phẫu thuật thay chỏm xương quay kim loại nhân tạo (Radial head arthroplasty) để phục hồi độ vững chống trượt khớp khuỷu và duy trì chiều dài xương quay.",
        "management": "Phẫu thuật thay chỏm xương quay kim loại nhân tạo (Radial head arthroplasty) để phục hồi độ vững chống trượt khớp khuỷu và duy trì chiều dài xương quay.",
        "technique_id": "12-6",
        "technique_title": "Radial Head Arthroplasty",
        "button_label": "Xem Kỹ thuật 12-6 (Thay chỏm xương quay nhân tạo)"
      },
      {
        "type": "Type IV",
        "code": "Type IV",
        "name": "Gãy chỏm quay KÈM TRẬT KHỚP KHUỶU (Tam chứng Terrible Triad)",
        "description": "Gãy chỏm xương quay nằm trong bệnh cảnh trật khớp khuỷu phức tạp (thường kèm gãy mỏm vẹt và rách phức hợp dây chằng bên ngoài LCL).",
        "desc": "Gãy chỏm quay KÈM TRẬT KHỚP KHUỶU (Tam chứng Terrible Triad)",
        "principles": "Nắn trật khớp khuỷu, thay chỏm quay hoặc kết hợp xương, khâu neo phục hồi dây chằng bên ngoài (LCL) và nẹp mỏm vẹt.",
        "management": "Nắn trật khớp khuỷu, thay chỏm quay hoặc kết hợp xương, khâu neo phục hồi dây chằng bên ngoài (LCL) và nẹp mỏm vẹt.",
        "technique_id": "12-6",
        "technique_title": "Radial Head Arthroplasty",
        "button_label": "Xem Kỹ thuật 12-6 (Thay chỏm quay & Khâu phục hồi dây chằng)"
      }
    ],
    "techniques": ["57-9", "57-10", "12-6"]
  },
  {
    "id": "ao_ota",
    "name": "Hệ thống phân loại AO/OTA toàn diện",
    "en_name": "AO/OTA Comprehensive Fracture Classification",
    "bone": "Whole Skeleton (Long Bones)",
    "bone_vi": "Toàn bộ khung xương (Xương dài)",
    "svg_ids": ["HumerusLeft", "HumerusRight", "l_Humerus", "RadiusLeft", "RadiusRight", "l_Radius", "UlnaLeft", "UlnaRight", "l_Ulna", "FemurLeft", "FemurRight", "l_Femur", "TibiaLeft", "TibiaRight", "l_Tibia", "FibulaLeft", "FibulaRight", "l_Fibula"],
    "category": "Trauma & Fracture Reconstruction",
    "chapter": 53,
    "chapter_title": "General Principles of Fracture Treatment",
    "pdf_page": 2989,
    "book_page": "2680",
    "description": "Hệ thống phân loại chuẩn hóa toàn cầu của Hiệp hội Chấn thương Chỉnh hình Quốc tế (AO Foundation & OTA). Mã hóa giải phẫu theo cấu trúc: [Xương][Đoạn][Kiểu A/B/C]. Xương: 1=Cánh tay, 2=Cẳng tay, 3=Xương đùi, 4=Cẳng chân. Đoạn: 1=Đầu gần, 2=Thân xương, 3=Đầu xa, 4=Mắt cá.",
    "types": [
      {
        "type": "AO 11",
        "code": "AO 11",
        "name": "Đầu gần xương cánh tay (Proximal Humerus - 11A/B/C)",
        "description": "Gãy đầu trên xương cánh tay bao gồm ngoài khớp 1 ổ (11A), ngoài khớp 2 ổ (11B), và gãy phạm khớp (11C).",
        "desc": "Gãy đầu trên xương cánh tay bao gồm ngoài khớp 1 ổ (11A), ngoài khớp 2 ổ (11B), và gãy phạm khớp (11C).",
        "principles": "Nắn chỉnh giải phẫu kết hợp xương nẹp khóa đầu trên xương cánh tay (PHILOS) hoặc đinh nội tủy có chốt.",
        "management": "Nắn chỉnh giải phẫu kết hợp xương nẹp khóa đầu trên xương cánh tay (PHILOS) hoặc đinh nội tủy có chốt.",
        "technique_id": "57-4",
        "technique_title": "Open Reduction and Internal Fixation of Proximal Humeral Fractures",
        "button_label": "Xem Kỹ thuật 57-4 (ORIF Nẹp khóa PHILOS 11)"
      },
      {
        "type": "AO 12",
        "code": "AO 12",
        "name": "Thân xương cánh tay (Humeral Shaft - 12A/B/C)",
        "description": "Gãy thân xương cánh tay: Gãy đơn giản (12A), gãy có mảnh chêm chéo (12B), gãy nhiều mảnh phức tạp (12C).",
        "desc": "Gãy thân xương cánh tay: Gãy đơn giản (12A), gãy có mảnh chêm chéo (12B), gãy nhiều mảnh phức tạp (12C).",
        "principles": "Kết hợp xương nẹp nén ép động (DCP) hoặc đinh nội tủy xuôi dòng. Cẩn thận bảo vệ thần kinh quay.",
        "management": "Kết hợp xương nẹp nén ép động (DCP) hoặc đinh nội tủy xuôi dòng. Cẩn thận bảo vệ thần kinh quay.",
        "technique_id": "57-6",
        "technique_title": "Open Reduction and Internal Fixation of the Humeral Shaft",
        "button_label": "Xem Kỹ thuật 57-6 (ORIF Thân xương cánh tay 12)"
      },
      {
        "type": "AO 13",
        "code": "AO 13",
        "name": "Đầu xa xương cánh tay (Distal Humerus - 13A/B/C)",
        "description": "Gãy trên lồi cầu và liên lồi cầu cánh tay: Ngoài khớp (13A), phạm khớp 1 phần (13B), phạm khớp hoàn toàn (13C).",
        "desc": "Gãy trên lồi cầu và liên lồi cầu cánh tay: Ngoài khớp (13A), phạm khớp 1 phần (13B), phạm khớp hoàn toàn (13C).",
        "principles": "Mổ mở mở xương mỏm khuỷu, nắn phẳng diện khớp và cố định bằng hai nẹp khóa vuông góc hoặc song song.",
        "management": "Mổ mở mở xương mỏm khuỷu, nắn phẳng diện khớp và cố định bằng hai nẹp khóa vuông góc hoặc song song.",
        "technique_id": "57-8",
        "technique_title": "Open Reduction and Internal Fixation of the Distal Humerus with Olecranon Osteotomy",
        "button_label": "Xem Kỹ thuật 57-8 (ORIF Đầu dưới cánh tay mở mỏm khuỷu 13)"
      },
      {
        "type": "AO 21",
        "code": "AO 21",
        "name": "Đầu gần xương quay & xương trụ (Proximal Radius/Ulna - 21A/B/C)",
        "description": "Gãy mỏm khuỷu, mỏm vẹt và chỏm quay: Ngoài khớp (21A), phạm khớp 1 xương (21B), phạm khớp cả hai xương (21C).",
        "desc": "Gãy mỏm khuỷu, mỏm vẹt và chỏm quay: Ngoài khớp (21A), phạm khớp 1 xương (21B), phạm khớp cả hai xương (21C).",
        "principles": "Néo ép số 8 hoặc nẹp khóa mỏm khuỷu; bắt ốc chìm không đầu hoặc thay chỏm quay nhân tạo.",
        "management": "Néo ép số 8 hoặc nẹp khóa mỏm khuỷu; bắt ốc chìm không đầu hoặc thay chỏm quay nhân tạo.",
        "technique_id": "57-9",
        "technique_title": "Open Reduction and Internal Fixation of Radial Head Fracture",
        "button_label": "Xem Kỹ thuật 57-9 (ORIF Đầu trên cẳng tay 21)"
      },
      {
        "type": "AO 22",
        "code": "AO 22",
        "name": "Thân hai xương cẳng tay (Diaphyseal Radius & Ulna - 22A/B/C)",
        "description": "Gãy thân xương quay và trụ: Gãy 1 xương (22A), gãy 1 xương có mảnh chêm (22B), gãy cả 2 xương phức tạp (22C).",
        "desc": "Gãy thân xương quay và trụ: Gãy 1 xương (22A), gãy 1 xương có mảnh chêm (22B), gãy cả 2 xương phức tạp (22C).",
        "principles": "Nắn chỉnh giải phẫu tuyệt đối chiều dài và độ cong quay, nẹp nén ép LC-DCP 3.5mm hai đường mổ độc lập.",
        "management": "Nắn chỉnh giải phẫu tuyệt đối chiều dài và độ cong quay, nẹp nén ép LC-DCP 3.5mm hai đường mổ độc lập.",
        "technique_id": "57-12",
        "technique_title": "Open Reduction and Internal Fixation of Both-Bone Forearm Fractures",
        "button_label": "Xem Kỹ thuật 57-12 (ORIF Thân hai xương cẳng tay 22)"
      },
      {
        "type": "AO 23",
        "code": "AO 23",
        "name": "Đầu xa xương quay & xương trụ (Distal Radius/Ulna - 23A/B/C)",
        "description": "Gãy đầu dưới xương quay: Ngoài khớp (23A), phạm khớp một phần (23B), phạm khớp hoàn toàn (23C).",
        "desc": "Gãy đầu dưới xương quay: Ngoài khớp (23A), phạm khớp một phần (23B), phạm khớp hoàn toàn (23C).",
        "principles": "Nẹp khóa mặt lòng (Volar locking plate 2.4mm/3.5mm) phục hồi góc nghiêng mặt khớp và chiều dài xương quay.",
        "management": "Nẹp khóa mặt lòng (Volar locking plate 2.4mm/3.5mm) phục hồi góc nghiêng mặt khớp và chiều dài xương quay.",
        "technique_id": "57-15",
        "technique_title": "Volar Plate Fixation of Fracture of the Distal Radius (Chung)",
        "button_label": "Xem Kỹ thuật 57-15 (Nẹp khóa Volar đầu dưới xương quay 23)"
      },
      {
        "type": "AO 31",
        "code": "AO 31",
        "name": "Đầu gần xương đùi (Proximal Femur - 31A/B/C)",
        "description": "Gãy vùng mấu chuyển (31A), gãy cổ xương đùi (31B), và gãy chỏm xương đùi (31C).",
        "desc": "Gãy vùng mấu chuyển (31A), gãy cổ xương đùi (31B), và gãy chỏm xương đùi (31C).",
        "principles": "Đinh nội tủy PFNA/Intertan cho mấu chuyển; vít xốp rỗng/DHS cho cổ đùi; thay khớp háng nếu di lệch ở người già.",
        "management": "Đinh nội tủy PFNA/Intertan cho mấu chuyển; vít xốp rỗng/DHS cho cổ đùi; thay khớp háng nếu di lệch ở người già.",
        "technique_id": "55-1",
        "technique_title": "Fixation of Femoral Neck Fracture with Cannulated Screws",
        "button_label": "Xem Kỹ thuật 55-1 (Cố định đầu trên xương đùi 31)"
      },
      {
        "type": "AO 32",
        "code": "AO 32",
        "name": "Thân xương đùi (Femoral Shaft - 32A/B/C)",
        "description": "Gãy thân xương đùi: Gãy đơn giản (32A), gãy có mảnh chêm (32B), gãy nhiều mảnh phức tạp (32C).",
        "desc": "Gãy thân xương đùi: Gãy đơn giản (32A), gãy có mảnh chêm (32B), gãy nhiều mảnh phức tạp (32C).",
        "principles": "Tiêu chuẩn vàng: Đóng đinh nội tủy có chốt xuôi dòng (Antegrade femoral nailing) có doa ống tủy.",
        "management": "Tiêu chuẩn vàng: Đóng đinh nội tủy có chốt xuôi dòng (Antegrade femoral nailing) có doa ống tủy.",
        "technique_id": "54-30",
        "technique_title": "Antegrade Femoral Nailing",
        "button_label": "Xem Kỹ thuật 54-30 (Đinh nội tủy thân xương đùi 32)"
      },
      {
        "type": "AO 33",
        "code": "AO 33",
        "name": "Đầu xa xương đùi (Distal Femur - 33A/B/C)",
        "description": "Gãy trên và liên lồi cầu đùi: Ngoài khớp (33A), phạm khớp 1 lồi cầu Hoffa (33B), phạm khớp hoàn toàn (33C).",
        "desc": "Gãy trên và liên lồi cầu đùi: Ngoài khớp (33A), phạm khớp 1 lồi cầu Hoffa (33B), phạm khớp hoàn toàn (33C).",
        "principles": "Nẹp khóa lồi cầu ngoài ít xâm lấn (LISS / Locking Condylar Plate) hoặc đinh nội tủy ngược dòng.",
        "management": "Nẹp khóa lồi cầu ngoài ít xâm lấn (LISS / Locking Condylar Plate) hoặc đinh nội tủy ngược dòng.",
        "technique_id": "54-27",
        "technique_title": "Submuscular Minimally Invasive Locking Condylar Plate Application",
        "button_label": "Xem Kỹ thuật 54-27 (Nẹp khóa đầu dưới xương đùi 33)"
      },
      {
        "type": "AO 41",
        "code": "AO 41",
        "name": "Đầu gần xương chày (Proximal Tibia / Plateau - 41A/B/C)",
        "description": "Gãy mâm chày: Ngoài khớp (41A), phạm khớp một phần (41B), phạm khớp hoàn toàn hai mâm chày (41C).",
        "desc": "Gãy mâm chày: Ngoài khớp (41A), phạm khớp một phần (41B), phạm khớp hoàn toàn hai mâm chày (41C).",
        "principles": "Nâng lún sụn khớp, ghép xương và cố định nẹp khóa nâng đỡ hoặc hai nẹp (Dual plating).",
        "management": "Nâng lún sụn khớp, ghép xương và cố định nẹp khóa nâng đỡ hoặc hai nẹp (Dual plating).",
        "technique_id": "54-14",
        "technique_title": "Open Reduction and Fixation of a Lateral Tibial Plateau Fracture",
        "button_label": "Xem Kỹ thuật 54-14 (ORIF Mâm chày đầu trên xương chày 41)"
      },
      {
        "type": "AO 42",
        "code": "AO 42",
        "name": "Thân xương cẳng chân (Tibial Shaft - 42A/B/C)",
        "description": "Gãy thân xương chày: Gãy đơn giản (42A), gãy có mảnh chêm (42B), gãy nhiều mảnh phức tạp (42C).",
        "desc": "Gãy thân xương chày: Gãy đơn giản (42A), gãy có mảnh chêm (42B), gãy nhiều mảnh phức tạp (42C).",
        "principles": "Đóng đinh nội tủy có chốt tĩnh có doa (Reamed intramedullary nailing) bảo tồn màng xương.",
        "management": "Đóng đinh nội tủy có chốt tĩnh có doa (Reamed intramedullary nailing) bảo tồn màng xương.",
        "technique_id": "54-11",
        "technique_title": "Intramedullary Nailing of Tibial Shaft Fractures",
        "button_label": "Xem Kỹ thuật 54-11 (Đinh nội tủy thân xương chày 42)"
      },
      {
        "type": "AO 43",
        "code": "AO 43",
        "name": "Đầu xa xương chày (Distal Tibia / Pilon - 43A/B/C)",
        "description": "Gãy Pilon chày trần khớp cổ chân: Ngoài khớp (43A), phạm khớp một phần (43B), vỡ nát phạm khớp hoàn toàn (43C).",
        "desc": "Gãy Pilon chày trần khớp cổ chân: Ngoài khớp (43A), phạm khớp một phần (43B), vỡ nát phạm khớp hoàn toàn (43C).",
        "principles": "Phẫu thuật hai thì: Thì 1 khung cố định ngoài bắc cầu cổ chân; Thì 2 nẹp khóa giải phẫu pilon khi da hết phù nề.",
        "management": "Phẫu thuật hai thì: Thì 1 khung cố định ngoài bắc cầu cổ chân; Thì 2 nẹp khóa giải phẫu pilon khi da hết phù nề.",
        "technique_id": "54-7",
        "technique_title": "Staged Minimally Invasive Open Reduction and Internal Fixation",
        "button_label": "Xem Kỹ thuật 54-7 (ORIF Hai thì gãy Pilon chày 43)"
      },
      {
        "type": "AO 44",
        "code": "AO 44",
        "name": "Vùng mắt cá cổ chân (Malleolar Segment - 44A/B/C)",
        "description": "Gãy mắt cá chân: Dưới khớp chày mác (44A), ngang mức khớp chày mác (44B), trên mức khớp chày mác (44C).",
        "desc": "Gãy mắt cá chân: Dưới khớp chày mác (44A), ngang mức khớp chày mác (44B), trên mức khớp chày mác (44C).",
        "principles": "Nắn chỉnh giải phẫu mác và mắt cá trong, cố định nẹp 1/3 ống và bắt vít khớp chày mác dưới nếu mất vững.",
        "management": "Nắn chỉnh giải phẫu mác và mắt cá trong, cố định nẹp 1/3 ống và bắt vít khớp chày mác dưới nếu mất vững.",
        "technique_id": "54-1",
        "technique_title": "Fixation of the Lateral Malleolus",
        "button_label": "Xem Kỹ thuật 54-1 (ORIF Vùng mắt cá cổ chân 44)"
      }
    ],
    "techniques": ["57-4", "57-6", "57-8", "57-9", "57-12", "57-15", "55-1", "54-30", "54-27", "54-14", "54-11", "54-7", "54-1"]
  },
  {
    "id": "salter_harris",
    "name": "Phân loại Salter-Harris (Sụn tiếp hợp trẻ em)",
    "en_name": "Salter-Harris Physeal Fracture Classification",
    "bone": "Physis / Pediatric Skeleton",
    "bone_vi": "Sụn tiếp hợp & Xương trẻ em",
    "svg_ids": ["FemurLeft", "FemurRight", "l_Femur", "TibiaLeft", "TibiaRight", "l_Tibia", "RadiusLeft", "RadiusRight", "l_Radius", "HumerusLeft", "HumerusRight", "l_Humerus"],
    "category": "Pediatrics",
    "chapter": 36,
    "chapter_title": "Fractures and Dislocations in Children",
    "pdf_page": 1695,
    "book_page": "1530",
    "description": "Phân loại kinh điển tổn thương sụn tăng trưởng (physis) ở trẻ em, tiên lượng nguy cơ rối loạn phát triển chiều dài chi và biến dạng góc xương (SALTR mnemonic).",
    "types": [
      {
        "type": "Type I",
        "code": "Type I",
        "name": "Tách rời sụn tăng trưởng thuần túy (Same / Straight across)",
        "description": "Đường gãy trượt tách hoàn toàn qua lớp tế bào phì đại của đĩa sụn tiếp hợp. Không có mảnh xương gãy kèm theo.",
        "desc": "Đường gãy trượt tách hoàn toàn qua lớp tế bào phì đại của đĩa sụn tiếp hợp. Không có mảnh xương gãy kèm theo.",
        "principles": "Nắn chỉnh kín nhẹ nhàng, bất động bó bột hoặc xuyên kim Kirschner trơn qua da. Tiên lượng liền tốt, hiếm khi ngắn chi.",
        "management": "Nắn chỉnh kín nhẹ nhàng, bất động bó bột hoặc xuyên kim Kirschner trơn qua da. Tiên lượng liền tốt, hiếm khi ngắn chi.",
        "technique_id": "36-7",
        "technique_title": "Percutaneous Pinning of Supracondylar Fractures (Flynn et al.)",
        "button_label": "Xem Kỹ thuật 36-7 (Nắn kín & Xuyên kim trơn qua da)"
      },
      {
        "type": "Type II",
        "code": "Type II",
        "name": "Gãy qua sụn lan lên hành xương (Above / Thurston-Holland sign)",
        "description": "Thể thường gặp nhất (chiếm 75%). Đường gãy chạy dọc đĩa sụn rồi bẻ góc đi lên hành xương tạo mảnh tam giác xương Thurston-Holland.",
        "desc": "Thể thường gặp nhất (chiếm 75%). Đường gãy chạy dọc đĩa sụn rồi bẻ góc đi lên hành xương tạo mảnh tam giác xương Thurston-Holland.",
        "principles": "Nắn chỉnh kín nhẹ nhàng trong 7 ngày đầu để tránh làm tổn thương thêm lớp tế bào sinh sản, bó bột hoặc xuyên đinh chéo qua mảnh hành xương.",
        "management": "Nắn chỉnh kín nhẹ nhàng trong 7 ngày đầu để tránh làm tổn thương thêm lớp tế bào sinh sản, bó bột hoặc xuyên đinh chéo qua mảnh hành xương.",
        "technique_id": "36-7",
        "technique_title": "Percutaneous Pinning of Supracondylar Fractures (Flynn et al.)",
        "button_label": "Xem Kỹ thuật 36-7 (Xuyên đinh chéo hành xương)"
      },
      {
        "type": "Type III",
        "code": "Type III",
        "name": "Gãy qua sụn lan xuống đầu xương mặt khớp (Lower)",
        "description": "Đường gãy nội khớp đi từ mặt khớp xuyên qua đầu xương rồi rẽ ngang qua đĩa sụn tiếp hợp ra ngoài. Thường gặp ở đầu dưới xương chày (gãy Tillaux).",
        "desc": "Đường gãy qua sụn lan xuống đầu xương mặt khớp (Lower)",
        "principles": "Bắt buộc nắn chỉnh giải phẫu mặt khớp tuyệt đối. Mổ mở kết hợp xương bằng vít xốp song song với đĩa sụn, tuyệt đối không bắt vít xuyên qua sụn tăng trưởng.",
        "management": "Bắt buộc nắn chỉnh giải phẫu mặt khớp tuyệt đối. Mổ mở kết hợp xương bằng vít xốp song song với đĩa sụn, tuyệt đối không bắt vít xuyên qua sụn tăng trưởng.",
        "technique_id": "36-9",
        "technique_title": "Open Reduction and Internal Fixation (lateral condyle / physeal)",
        "button_label": "Xem Kỹ thuật 36-9 (ORIF Nắn phẳng mặt khớp & Bắt vít song song sụn)"
      },
      {
        "type": "Type IV",
        "code": "Type IV",
        "name": "Gãy xuyên qua hành xương, đĩa sụn và đầu xương (Through)",
        "description": "Đường gãy chạy dọc cắt ngang qua cả 3 vùng: hành xương, đĩa sụn tăng trưởng và đầu xương mặt khớp. Nguy cơ hình thành cầu xương (physeal bar) gây vẹo trục chi.",
        "desc": "Gãy xuyên qua hành xương, đĩa sụn và đầu xương (Through)",
        "principles": "Mổ mở nắn chỉnh giải phẫu hoàn hảo cả diện khớp và màng xương đĩa sụn, cố định bằng kim trơn hoặc vít xốp ở hành xương và đầu xương.",
        "management": "Mổ mở nắn chỉnh giải phẫu hoàn hảo cả diện khớp và màng xương đĩa sụn, cố định bằng kim trơn hoặc vít xốp ở hành xương và đầu xương.",
        "technique_id": "36-9",
        "technique_title": "Open Reduction and Internal Fixation (lateral condyle / physeal)",
        "button_label": "Xem Kỹ thuật 36-9 (Mổ mở nắn phục hồi đĩa sụn & Cố định)"
      },
      {
        "type": "Type V",
        "code": "Type V",
        "name": "Gãy nén ép hủy hoại đĩa sụn tiếp hợp (cRushed)",
        "description": "Lực nén ép dọc trục cực mạnh nghiền nát lớp tế bào mầm của đĩa sụn tiếp hợp. Trên X-quang ban đầu khó phát hiện nhưng để lại hậu quả ngừng phát triển xương.",
        "desc": "Gãy nén ép hủy hoại đĩa sụn tiếp hợp (cRushed)",
        "principles": "Bất động bột không tỳ đè hoàn toàn, theo dõi chụp phim định kỳ mỗi 3-6 tháng để phát hiện sớm cầu xương dính và can thiệp đục cầu xương (Langenskiöld procedure).",
        "management": "Bất động bột không tỳ đè hoàn toàn, theo dõi chụp phim định kỳ mỗi 3-6 tháng để phát hiện sớm cầu xương dính và can thiệp đục cầu xương (Langenskiöld procedure).",
        "technique_id": "36-16",
        "technique_title": "Open Reduction and Internal Fixation of Physeal Injuries",
        "button_label": "Xem Kỹ thuật 36-16 (Bất động bảo vệ & Phẫu thuật cầu sụn)"
      }
    ],
    "techniques": ["36-7", "36-8", "36-9", "36-16", "36-34"]
  },
  {
    "id": "pipkin",
    "name": "Phân loại Pipkin",
    "en_name": "Pipkin Femoral Head Fracture Classification",
    "bone": "Femur (Head)",
    "bone_vi": "Chỏm xương đùi",
    "svg_ids": ["FemurLeft", "FemurRight", "l_Femur", "PelvicGirdle", "l_Pelvic_Girdle"],
    "category": "Hip & Pelvis",
    "chapter": 55,
    "chapter_title": "Fractures and Dislocations of the Hip",
    "pdf_page": 3180,
    "book_page": "2856",
    "description": "Phân loại gãy chỏm xương đùi trong chấn thương trật khớp háng ra sau (cơ chế đập đầu gối vào táp-lô), đánh giá vị trí mảnh vỡ so với hố chỏm và tổn thương cổ xương đùi hoặc ổ cối phối hợp.",
    "types": [
      {
        "type": "Pipkin I",
        "code": "Pipkin I",
        "name": "Gãy chỏm xương đùi DƯỚI hố chỏm (Caudad to Fovea)",
        "description": "Mảnh gãy vỡ nằm ở nửa dưới chỏm xương đùi, không thuộc diện sụn tỳ đè chịu lực chính của khớp háng.",
        "desc": "Mảnh gãy vỡ nằm ở nửa dưới chỏm xương đùi, không thuộc diện sụn tỳ đè chịu lực chính của khớp háng.",
        "principles": "Nắn trật khớp háng cấp cứu. Mảnh gãy nhỏ không kẹt khớp: Điều trị bảo tồn; Mảnh gãy lớn di lệch hoặc kẹt khớp: Bắt vít chìm hoặc lấy bỏ mảnh rời.",
        "management": "Nắn trật khớp háng cấp cứu. Mảnh gãy nhỏ không kẹt khớp: Điều trị bảo tồn; Mảnh gãy lớn di lệch hoặc kẹt khớp: Bắt vít chìm hoặc lấy bỏ mảnh rời.",
        "technique_id": "55-10",
        "technique_title": "Open Reduction of Posterior Hip Dislocation Through a Posterior Approach",
        "button_label": "Xem Kỹ thuật 55-10 (Nắn trật lối sau & Bắt ốc chìm)"
      },
      {
        "type": "Pipkin II",
        "code": "Pipkin II",
        "name": "Gãy chỏm xương đùi TRÊN hố chỏm (Cephalad to Fovea)",
        "description": "Đường gãy nằm ở nửa trên chỏm xương đùi, liên quan trực tiếp đến diện chịu lực chính của khớp háng.",
        "desc": "Đường gãy nằm ở nửa trên chỏm xương đùi, liên quan trực tiếp đến diện chịu lực chính của khớp háng.",
        "principles": "Bắt buộc mổ mở nắn chỉnh giải phẫu tuyệt đối qua đường mổ trật khớp háng bảo tồn mạch (Ganz surgical hip dislocation), cố định bằng vít tự tiêu hoặc vít chìm không đầu dưới mặt sụn.",
        "management": "Bắt buộc mổ mở nắn chỉnh giải phẫu tuyệt đối qua đường mổ trật khớp háng bảo tồn mạch (Ganz surgical hip dislocation), cố định bằng vít tự tiêu hoặc vít chìm không đầu dưới mặt sụn.",
        "technique_id": "6-1",
        "technique_title": "Surgical Dislocation of the Hip (Ganz et al.)",
        "button_label": "Xem Kỹ thuật 6-1 (Trật khớp háng bảo tồn mạch Ganz & Bắt ốc)"
      },
      {
        "type": "Pipkin III",
        "code": "Pipkin III",
        "name": "Gãy chỏm xương đùi KÈM GÃY CỔ XƯƠNG ĐÙI",
        "description": "Tổn thương kết hợp Pipkin I hoặc II kèm gãy cổ xương đùi. Nguy cơ hoại tử vô mạch chỏm và tiêu cổ xương đùi cực kỳ cao (>90%).",
        "desc": "Gãy chỏm xương đùi KÈM GÃY CỔ XƯƠNG ĐÙI",
        "principles": "Người trẻ tuổi: Nắn mở kết hợp xương cổ đùi và chỏm thật cẩn thận; Người lớn tuổi: Chỉ định thay khớp háng toàn phần (THA) thì đầu.",
        "management": "Người trẻ tuổi: Nắn mở kết hợp xương cổ đùi và chỏm thật cẩn thận; Người lớn tuổi: Chỉ định thay khớp háng toàn phần (THA) thì đầu.",
        "technique_id": "55-1",
        "technique_title": "Fixation of Femoral Neck Fracture with Cannulated Screws",
        "button_label": "Xem Kỹ thuật 55-1 (Cố định cổ xương đùi / Thay khớp háng)"
      },
      {
        "type": "Pipkin IV",
        "code": "Pipkin IV",
        "name": "Gãy chỏm xương đùi KÈM VỠ THÀNH SAU Ổ CỐI",
        "description": "Tổn thương phối hợp Pipkin I hoặc II kèm vỡ thành sau hoặc cột sau ổ cối, khớp háng hoàn toàn mất vững sau nắn.",
        "desc": "Gãy chỏm xương đùi KÈM VỠ THÀNH SAU Ổ CỐI",
        "principles": "Mổ mở qua đường mổ Kocher-Langenbeck, kết hợp xương nẹp nâng đỡ thành sau ổ cối và bắt vít chìm cố định diện chỏm xương đùi.",
        "management": "Mổ mở qua đường mổ Kocher-Langenbeck, kết hợp xương nẹp nâng đỡ thành sau ổ cối và bắt vít chìm cố định diện chỏm xương đùi.",
        "technique_id": "56-2",
        "technique_title": "Fixation of Comminuted Posterior Wall Fracture with or without a Transverse Component",
        "button_label": "Xem Kỹ thuật 56-2 (Nẹp thành sau ổ cối & Cố định chỏm)"
      }
    ],
    "techniques": ["55-10", "55-1", "55-2", "6-1", "56-2"]
  },
  {
    "id": "sanders",
    "name": "Phân loại Sanders",
    "en_name": "Sanders Calcaneal Intraarticular Fracture Classification",
    "bone": "Calcaneus",
    "bone_vi": "Xương gót",
    "svg_ids": ["TarsalsLeft", "TarsalsRight", "l_Tarsals"],
    "category": "Foot & Ankle",
    "chapter": 88,
    "chapter_title": "Fractures and Dislocations of the Foot",
    "pdf_page": 4746,
    "book_page": "4280",
    "description": "Phân loại gãy xương gót nội khớp dựa trên phim cắt lớp vi tính (CT scan) mặt cắt Coronal tại vị trí rộng nhất của diện khớp sau dưới sên, chia diện khớp thành 3 cột A (ngoài), B (giữa), C (trong).",
    "types": [
      {
        "type": "Sanders Type I",
        "code": "Sanders Type I",
        "name": "Gãy nội khớp KHÔNG di lệch (< 2mm)",
        "description": "Bất kể có bao nhiêu đường gãy, diện sụn khớp dưới sên phía sau không bị di lệch hoặc di lệch dưới 2mm.",
        "desc": "Bất kể có bao nhiêu đường gãy, diện sụn khớp dưới sên phía sau không bị di lệch hoặc di lệch dưới 2mm.",
        "principles": "Điều trị bảo tồn: Bất động nẹp bột cẳng bàn chân, không tỳ đè trong 10-12 tuần, tập vận động sớm khớp cổ chân và dưới sên.",
        "management": "Điều trị bảo tồn: Bất động nẹp bột cẳng bàn chân, không tỳ đè trong 10-12 tuần, tập vận động sớm khớp cổ chân và dưới sên.",
        "technique_id": "88-5",
        "technique_title": "Percutaneous Reduction and Fixation of Calcaneal Fracture",
        "button_label": "Xem Kỹ thuật 88-5 (Điều trị bảo tồn / Nắn vít qua da)"
      },
      {
        "type": "Sanders Type II",
        "code": "Sanders Type II",
        "name": "Gãy 2 mảnh diện khớp sau (Một đường gãy nguyên phát: IIA / IIB / IIC)",
        "description": "Một đường gãy nội khớp nguyên phát chia diện khớp sau thành 2 mảnh: IIA (đường gãy phía ngoài), IIB (đường gãy ở giữa), IIC (đường gãy phía trong).",
        "desc": "Gãy 2 mảnh diện khớp sau (Một đường gãy nguyên phát: IIA / IIB / IIC)",
        "principles": "Mổ mở nắn chỉnh qua đường mổ chữ L ngoài mở rộng (Extensile lateral approach), nắn giải phẫu diện khớp, cố định nẹp khóa xương gót.",
        "management": "Mổ mở nắn chỉnh qua đường mổ chữ L ngoài mở rộng (Extensile lateral approach), nắn giải phẫu diện khớp, cố định nẹp khóa xương gót.",
        "technique_id": "88-1",
        "technique_title": "Open Reduction of Calcaneal Fracture (Benirschke and Sangeorzan)",
        "button_label": "Xem Kỹ thuật 88-1 (Mổ mở đường chữ L ngoài & Nẹp khóa gót)"
      },
      {
        "type": "Sanders Type III",
        "code": "Sanders Type III",
        "name": "Gãy 3 mảnh diện khớp sau (Hai đường gãy: IIIAB / IIIAC / IIIBC)",
        "description": "Hai đường gãy nội khớp tạo ra mảnh xương lún trung tâm nằm kẹt giữa hai mảnh ngoài và trong.",
        "desc": "Gãy 3 mảnh diện khớp sau (Hai đường gãy: IIIAB / IIIAC / IIIBC)",
        "principles": "Mổ mở nâng mảnh lún trung tâm, ghép xương xốp hoặc chất thay thế xương lấp đầy hốc rỗng, cố định nẹp nâng đỡ diện khớp.",
        "management": "Mổ mở nâng mảnh lún trung tâm, ghép xương xốp hoặc chất thay thế xương lấp đầy hốc rỗng, cố định nẹp nâng đỡ diện khớp.",
        "technique_id": "88-1",
        "technique_title": "Open Reduction of Calcaneal Fracture (Benirschke and Sangeorzan)",
        "button_label": "Xem Kỹ thuật 88-1 (Nâng mảnh diện khớp lún & Ghép xương)"
      },
      {
        "type": "Sanders Type IV",
        "code": "Sanders Type IV",
        "name": "Gãy nát vụn nhiều hơn 4 mảnh (Comminuted > 4 fragments)",
        "description": "Diện khớp sau vỡ vụn nghiêm trọng thành từ 4 mảnh trở lên, không còn khả năng tái tạo mặt phẳng diện sụn khớp nguyên vẹn.",
        "desc": "Gãy nát vụn nhiều hơn 4 mảnh (Comminuted > 4 fragments)",
        "principles": "Phẫu thuật hàn cứng khớp dưới sên thì đầu (Primary subtalar arthrodesis) kết hợp nẹp phục hồi chiều cao và chiều rộng gót.",
        "management": "Phẫu thuật hàn cứng khớp dưới sên thì đầu (Primary subtalar arthrodesis) kết hợp nẹp phục hồi chiều cao và chiều rộng gót.",
        "technique_id": "88-2",
        "technique_title": "Subtalar Arthrodesis",
        "button_label": "Xem Kỹ thuật 88-2 (Hàn cứng khớp dưới sên thì đầu)"
      }
    ],
    "techniques": ["88-1", "88-2", "88-3", "88-4", "88-5"]
  },
  {
    "id": "anderson_dalonzo",
    "name": "Phân loại Anderson - D'Alonzo",
    "en_name": "Anderson-D'Alonzo Odontoid Process Fracture Classification",
    "bone": "Cervical Spine (C2 Axis)",
    "bone_vi": "Đốt sống cổ C2 (Mỏm nha)",
    "svg_ids": ["ThoracicVertebrae", "LumbarVertebrae", "l_Thoracic_Vertebrae", "l_Lumbar_Vertebrae"],
    "category": "Spine",
    "chapter": 41,
    "chapter_title": "Fractures, Dislocations, and Fracture-Dislocations of the Spine",
    "pdf_page": 1979,
    "book_page": "1784",
    "description": "Phân loại gãy mỏm nha đốt sống trục C2 kinh điển nhất dựa trên vị trí giải phẫu của đường gãy, quyết định tỷ lệ liền xương và phương pháp phẫu thuật lối trước hay lối sau.",
    "types": [
      {
        "type": "Type I",
        "code": "Type I",
        "name": "Gãy vát chóp mỏm nha (Tip of Odontoid)",
        "description": "Đường gãy bong giật ở chóp mỏm nha tại điểm bám của dây chằng cánh (Alar ligament). Thể hiếm gặp, cơ học cột sống vững.",
        "desc": "Đường gãy bong giật ở chóp mỏm nha tại điểm bám của dây chằng cánh (Alar ligament). Thể hiếm gặp, cơ học cột sống vững.",
        "principles": "Bất động bảo tồn bằng nẹp cổ cứng Philadelphia hoặc khung Halo-vest trong 8-10 tuần. Tỷ lệ liền xương đạt gần 100%.",
        "management": "Bất động bảo tồn bằng nẹp cổ cứng Philadelphia hoặc khung Halo-vest trong 8-10 tuần. Tỷ lệ liền xương đạt gần 100%.",
        "technique_id": "41-3",
        "technique_title": "Halo Vest Application",
        "button_label": "Xem Kỹ thuật 41-3 (Bất động nẹp cổ cứng / Halo-vest)"
      },
      {
        "type": "Type II",
        "code": "Type II",
        "name": "Gãy ngang eo mỏm nha (Waist / Base of Odontoid)",
        "description": "Đường gãy đi ngang qua phần eo/cổ của mỏm nha nơi tiếp giáp với thân đốt sống C2. Thường gặp nhất (60%), tỷ lệ khớp giả rất cao (30-40%) do vùng cổ mỏm nha nghèo mạch máu nuôi dưỡng.",
        "desc": "Gãy ngang eo mỏm nha (Waist / Base of Odontoid)",
        "principles": "Phẫu thuật bắt 1-2 vít mỏm nha lối trước (Anterior odontoid screw fixation) để bảo tồn vận động xoay C1-C2; nếu gãy vụn hoặc loãng xương mổ hàn C1-C2 lối sau (Harms construct).",
        "management": "Phẫu thuật bắt 1-2 vít mỏm nha lối trước (Anterior odontoid screw fixation) để bảo tồn vận động xoay C1-C2; nếu gãy vụn hoặc loãng xương mổ hàn C1-C2 lối sau (Harms construct).",
        "technique_id": "41-8",
        "technique_title": "Anterior Odontoid Screw Fixation (Etter)",
        "button_label": "Xem Kỹ thuật 41-8 (Bắt vít mỏm nha lối trước Etter)"
      },
      {
        "type": "Type III",
        "code": "Type III",
        "name": "Gãy lan sâu vào thân đốt sống C2 (Body of C2)",
        "description": "Đường gãy đi xuống sâu vào vùng xương xốp của thân đốt sống C2. Diện tích tiếp xúc xương xốp rộng rãi.",
        "desc": "Đường gãy lan sâu vào thân đốt sống C2 (Body of C2)",
        "principles": "Bất động bằng khung Halo-vest hoặc nẹp Minerva trong 10-12 tuần. Tỷ lệ liền xương tự nhiên rất cao (>90%) nhờ tưới máu xương xốp dồi dào.",
        "management": "Bất động bằng khung Halo-vest hoặc nẹp Minerva trong 10-12 tuần. Tỷ lệ liền xương tự nhiên rất cao (>90%) nhờ tưới máu xương xốp dồi dào.",
        "technique_id": "41-3",
        "technique_title": "Halo Vest Application",
        "button_label": "Xem Kỹ thuật 41-3 (Bất động khung Halo-vest)"
      }
    ],
    "techniques": ["41-8", "41-6", "41-7", "41-10", "41-3"]
  }
]

def build():
    os.makedirs('data', exist_ok=True)
    with open('data/fracture_classifications.json', 'w', encoding='utf-8') as f:
        json.dump(FRACTURE_CLASSIFICATIONS, f, ensure_ascii=False, indent=2)
    print(f"Successfully generated {len(FRACTURE_CLASSIFICATIONS)} classifications in data/fracture_classifications.json")

if __name__ == '__main__':
    build()
